/* ===== FALLBEISPIEL-DATENBANK (Übungsmaterial – keine amtliche Vorgabe) ===== */
/* Kennzahlen bewusst gerundet/qualitativ; vor Verwendung im Unterricht mit aktuellen Quellen prüfen. */
window.CASES = [
{ id: "palmoel", name: "Palmöl auf Sumatra und Borneo", region: "Indonesien, Südostasien", lat: 0.5, lon: 102, topics: ["lw_trop", "lw_nach"], scale: "national / global",
  facts: ["Indonesien ist der weltweit größte Palmölproduzent.", "Anbau auf Plantagen und bei Kleinbauern, häufig nach Rodung von Regenwald und Torfmoor.", "Palmöl steckt in Lebensmitteln, Kosmetik und Biokraftstoffen."],
  causes: ["Hohe Weltmarktnachfrage", "Sehr hoher Flächenertrag der Ölpalme", "Staatliche Förderung als Exportsektor"],
  cons: ["Devisen und Einkommen, Infrastrukturausbau", "Entwaldung, Biodiversitätsverlust (z. B. Orang-Utan-Lebensraum)", "Torfbrände, CO₂-Emissionen, Rauchbelastung", "Landkonflikte mit indigenen Gemeinschaften"],
  actors: ["Plantagenkonzerne", "Kleinbäuerinnen und Kleinbauern", "Staat", "Indigene Gemeinschaften", "Umwelt-NGOs", "Konsumenten und Handel in Europa"],
  conflicts: ["Einkommen vs. Waldschutz", "Staatliche Konzessionen vs. traditionelle Landrechte"],
  sol: ["Zertifizierung (RSPO)", "Moratorien für Waldrodung", "Ertragssteigerung auf bestehenden Flächen", "Lieferkettengesetze (z. B. EU-Entwaldungsverordnung)"],
  sust: "Ökonomisch bedeutend, ökologisch und sozial problematisch; nachhaltig nur mit wirksamem Flächenschutz und Rechtssicherheit.",
  exam: "Typisch für: Tropische Landwirtschaft und Weltmarkt, Ressourcengefährdung, Beurteilung von Zertifizierungen.",
  atlas: "Suche im Atlas Karten zur Vegetation und Landnutzung Südostasiens." },
{ id: "kakao", name: "Kakao aus Côte d'Ivoire und Ghana", region: "Westafrika", lat: 7, lon: -5, topics: ["lw_trop", "disp"], scale: "national / global",
  facts: ["Côte d'Ivoire und Ghana liefern zusammen weit mehr als die Hälfte des Weltkakaos.", "Überwiegend kleinbäuerlicher Anbau.", "Verarbeitung zu Schokolade findet überwiegend in Europa und Nordamerika statt."],
  causes: ["Kolonial geprägte Exportorientierung", "Klimatische Eignung (immerfeuchte/wechselfeuchte Tropen)"],
  cons: ["Niedrige Einkommen der Produzenten, Kinderarbeit", "Abhängigkeit von Weltmarktpreisen", "Entwaldung für neue Anbauflächen"],
  actors: ["Kleinbauern", "Nationale Vermarktungsbehörden", "Handels- und Schokoladenkonzerne", "Fairtrade-Organisationen", "Konsumenten"],
  conflicts: ["Niedrige Rohstoffpreise vs. existenzsichernde Einkommen"],
  sol: ["Fairer Handel und Mindestpreise", "Verarbeitung im Land", "Agroforst-Kakao", "Lieferkettengesetze"],
  sust: "Soziale Nachhaltigkeit ist das Kernproblem; Wertschöpfung im Land und faire Preise gelten als Schlüssel.",
  exam: "Wertschöpfungskette, Terms of Trade, Fairer Handel.",
  atlas: "Karte Westafrika: Landwirtschaft und Klima." },
{ id: "almeria", name: "«Mar de plástico» in Almería", region: "Andalusien, Südspanien", lat: 36.8, lon: -2.5, topics: ["lw_int", "lw_nach"], scale: "regional",
  facts: ["Eine der größten Konzentrationen von Gewächshäusern der Welt, sogar aus dem All sichtbar.", "Ganzjähriger Gemüseanbau für den europäischen Markt.", "Semiarides Klima mit sehr geringen Niederschlägen."],
  causes: ["Viele Sonnenstunden, milde Winter", "Nähe zum EU-Binnenmarkt", "Grundwasser und Tropfbewässerung", "Günstige Arbeitskräfte (oft Migrantinnen und Migranten)"],
  cons: ["Wohlstand in einer früher armen Region", "Übernutzung des Grundwassers, Versalzung", "Plastikmüll", "Prekäre Arbeits- und Wohnbedingungen"],
  actors: ["Landwirtinnen und Landwirte, Kooperativen", "Saisonarbeitskräfte", "Handelsketten in Europa", "Wasserbehörden", "Umweltverbände"],
  conflicts: ["Wasserbedarf vs. Grundwasserschutz", "Niedrige Preise vs. faire Löhne"],
  sol: ["Meerwasserentsalzung", "Recycling von Folien", "Nützlingseinsatz statt Pestizide", "Arbeitsrechtliche Kontrollen"],
  sust: "Ökonomisch erfolgreich, ökologisch und sozial mit deutlichen Defiziten.",
  exam: "Intensivierung in den Subtropen, Bewässerung, Nachhaltigkeit erörtern.",
  atlas: "Spanien: Klima, Landwirtschaft, Bewässerungsgebiete." },
{ id: "oldenburg", name: "Veredelungsregion Oldenburger Münsterland", region: "Niedersachsen, Deutschland", lat: 52.8, lon: 8.1, topics: ["lw_int"], scale: "regional",
  facts: ["Sehr hohe Dichte an Schweine- und Geflügelhaltung.", "Agrobusiness-Cluster mit Futtermittelwerken, Schlachthöfen, Maschinenbau.", "Futtermittel (z. B. Soja) werden in großen Mengen importiert."],
  causes: ["Arme Sandböden (Geest) machten Veredelung attraktiver als Ackerbau", "Nähe zu Seehäfen für Futterimporte", "Clusterbildung"],
  cons: ["Hohe Wertschöpfung und Beschäftigung", "Gülleüberschüsse, Nitrat im Grundwasser", "Tierwohl- und Arbeitsbedingungsdebatten"],
  actors: ["Landwirtschaftliche Betriebe", "Agrarindustrie", "Wasserversorger", "Landesregierung", "Tierschutzorganisationen"],
  conflicts: ["Produktion vs. Grundwasserschutz"],
  sol: ["Düngeverordnung, Gülletransporte in Ackerbauregionen", "Reduktion der Tierbestände", "Tierwohlprogramme"],
  sust: "Ökonomisch stark, ökologisch belastet.",
  exam: "Veredelungswirtschaft, Agrobusiness, vertikale Integration.",
  atlas: "Deutschland: Landwirtschaft, Viehhaltung." },
{ id: "aral", name: "Aralsee", region: "Kasachstan / Usbekistan, Zentralasien", lat: 45, lon: 60, topics: ["lw_nach"], scale: "regional",
  facts: ["Einst einer der größten Binnenseen der Erde.", "Seit den 1960er-Jahren stark geschrumpft und in Teilseen zerfallen.", "Zuflüsse Amudarja und Syrdarja wurden für Baumwollbewässerung genutzt."],
  causes: ["Sowjetische Planwirtschaft mit Baumwoll-Monokultur", "Ineffiziente offene Kanäle mit hohen Verdunstungsverlusten"],
  cons: ["Zusammenbruch der Fischerei", "Salz- und Staubstürme, Gesundheitsprobleme", "Kontinentaleres Lokalklima", "Bodenversalzung"],
  actors: ["Anrainerstaaten", "Baumwollwirtschaft", "Fischerei", "Internationale Organisationen"],
  conflicts: ["Bewässerungslandwirtschaft vs. Seeerhalt", "Oberlieger vs. Unterlieger"],
  sol: ["Kokaral-Damm zur Stabilisierung des Nordaralsees", "Effizientere Bewässerung", "Anbau weniger wasserintensiver Kulturen"],
  sust: "Beispiel für nicht nachhaltige Ressourcennutzung; im Norden teilweise Erholung.",
  exam: "Syndrom-Ansatz, Ressourcengefährdung, Wasserkonflikte.",
  atlas: "Zentralasien: Physische Karte, Bewässerungsgebiete." },
{ id: "sahel", name: "Sahelzone und «Große Grüne Mauer»", region: "Afrika südlich der Sahara", lat: 14, lon: 0, topics: ["lw_klima", "lw_nach"], scale: "global / regional",
  facts: ["Übergangsraum zwischen Sahara und Savannen mit stark schwankenden Niederschlägen.", "Regenfeldbau und mobile Weidewirtschaft prägen die Landnutzung.", "Initiative der Afrikanischen Union für einen Vegetationsgürtel quer durch den Kontinent."],
  causes: ["Niederschlagsvariabilität, Klimawandel", "Bevölkerungswachstum und Übernutzung (Überweidung, Brennholz)"],
  cons: ["Ernteausfälle, Ernährungsunsicherheit", "Konflikte um Weide und Wasser", "Migration"],
  actors: ["Bäuerinnen, Bauern, Hirten", "Staaten der Region", "Afrikanische Union", "Geberländer, NGOs"],
  conflicts: ["Ackerbau vs. Weidewirtschaft", "Kurzfristige Ernährung vs. langfristiger Bodenschutz"],
  sol: ["Wiederbegrünung (u. a. Förderung natürlicher Baumverjüngung)", "Steinwälle und Zaï-Pflanzlöcher", "Dürreresistente Sorten"],
  sust: "Lokal erfolgreiche Ansätze, Gesamtziel noch weit verfehlt.",
  exam: "Klimawandel und Landwirtschaft, Desertifikation, Anpassung bewerten.",
  atlas: "Afrika: Klima, Vegetation, Niederschlagsvariabilität." },
{ id: "ruhr", name: "Ruhrgebiet", region: "Nordrhein-Westfalen, Deutschland", lat: 51.5, lon: 7.2, topics: ["ind_struk", "tert"], scale: "regional",
  facts: ["Größter Ballungsraum Deutschlands, entstanden durch Kohle und Stahl.", "Steinkohleförderung endete 2018 (Zeche Prosper-Haniel, Bottrop).", "Heute dicht besetzte Hochschullandschaft, Logistik, Gesundheitswirtschaft, Kultur."],
  causes: ["Kohle- und Stahlkrisen seit Ende der 1950er-Jahre", "Globale Konkurrenz", "Produktivitätssteigerung"],
  cons: ["Hohe Arbeitslosigkeit, Abwanderung", "Brachflächen, Altlasten", "Neue Nutzung als Kultur- und Freizeitorte (z. B. Zeche Zollverein, UNESCO-Welterbe)"],
  actors: ["Kommunen, Land, Regionalverband Ruhr", "Unternehmen", "Hochschulen", "Gewerkschaften"],
  conflicts: ["Erhalt alter Industriearbeitsplätze vs. Förderung neuer Branchen"],
  sol: ["Internationale Bauausstellung Emscher Park", "Technologie- und Gründerzentren", "Umbau der Emscher", "Strukturhilfen zum Kohleausstieg"],
  sust: "Fortschritte in Umwelt und Image; wirtschaftliche Aufholung bleibt unvollständig.",
  exam: "Strukturwandel, weiche Standortfaktoren, Revitalisierung.",
  atlas: "Nordrhein-Westfalen: Wirtschaft, Ruhrgebiet im Wandel." },
{ id: "shenzhen", name: "Shenzhen und das Perlflussdelta", region: "Guangdong, China", lat: 22.5, lon: 114.1, topics: ["ind_wachs", "metro"], scale: "regional / global",
  facts: ["1980 als eine der ersten Sonderwirtschaftszonen Chinas eingerichtet.", "Entwicklung vom Fischerort zur Millionenmetropole und zum Elektronik- und Tech-Zentrum.", "Teil der Greater Bay Area mit Hongkong und Guangzhou."],
  causes: ["Politische Öffnung, Steuer- und Zollvorteile", "Nähe zu Hongkong (Kapital, Hafen)", "Große Zahl von Binnenmigrantinnen und -migranten"],
  cons: ["Hohe Wachstumsraten, Aufstieg von Tech-Konzernen", "Umweltbelastung, Flächenverbrauch", "Soziale Ungleichheit (Hukou-System)"],
  actors: ["Zentral- und Provinzregierung", "Unternehmen", "Wanderarbeitskräfte", "Investoren"],
  conflicts: ["Wachstum vs. Umwelt", "Städtische Einwohner vs. Wanderarbeitskräfte"],
  sol: ["Aufwertung zu Forschung und Innovation", "Umweltauflagen"],
  sust: "Ökonomisch sehr erfolgreich; ökologische und soziale Kosten hoch.",
  exam: "Wachstumsregionen, Sonderwirtschaftszone, Cluster.",
  atlas: "China: Wirtschaft, Bevölkerungsdichte, Perlflussdelta." },
{ id: "innenstadt", name: "Innenstädte im Onlinehandel", region: "Deutsche Mittelstädte (Themenbeispiel)", lat: 51.2, lon: 10, topics: ["digital", "stadt_merk"], scale: "lokal",
  facts: ["Onlinehandel gewinnt Marktanteile, besonders bei Mode und Elektronik.", "Zunehmender Leerstand in Einkaufsstraßen kleinerer Städte.", "Parallel wachsen Logistikflächen an Autobahnen."],
  causes: ["Bequemlichkeit, Preisvergleich, Pandemieeffekt", "Hohe Mieten in 1A-Lagen"],
  cons: ["Leerstand, Verödung", "Mehr Lieferverkehr", "Neue Nutzungen: Gastronomie, Wohnen, Kultur, Bildung"],
  actors: ["Einzelhandel", "Eigentümer", "Kommunen", "Onlinehändler, Paketdienste", "Bürgerinnen und Bürger"],
  conflicts: ["Hohe Mieterwartungen vs. neue Nutzungen", "Lieferverkehr vs. Aufenthaltsqualität"],
  sol: ["Innenstadtmanagement, Zwischennutzungen", "Mischnutzung, Wohnen in Obergeschossen", "Mikro-Depots und Lastenräder"],
  sust: "Chance zur Neuerfindung der Innenstadt, wenn Nutzungen gemischt werden.",
  exam: "Digitalisierung und Stadt, Standortfaktoren des Einzelhandels.",
  atlas: "Deutschland: Verkehrsnetz, Verdichtungsräume." },
{ id: "bengaluru", name: "Bengaluru (Bangalore)", region: "Karnataka, Indien", lat: 12.97, lon: 77.59, topics: ["tert", "digital", "ind_wachs"], scale: "regional / global",
  facts: ["Bedeutendes IT- und Dienstleistungszentrum Indiens («Silicon Valley Indiens»).", "Standort von Software-, Outsourcing- und Forschungsunternehmen.", "Sehr schnelles Stadtwachstum."],
  causes: ["Englischsprachige, gut ausgebildete Fachkräfte", "Niedrigere Lohnkosten", "Staatliche Förderung, Hochschulen", "Zeitverschiebung ermöglicht Rund-um-die-Uhr-Service"],
  cons: ["Neue Mittelschicht", "Verkehrsüberlastung, Wasserknappheit", "Starke soziale Gegensätze, informelle Siedlungen"],
  actors: ["IT-Konzerne", "Start-ups", "Bundesstaat", "Stadtverwaltung", "Beschäftigte, Migrierte"],
  conflicts: ["Wachstum vs. Infrastruktur und Wasser"],
  sol: ["Metro-Ausbau", "Satellitenstädte", "Wassermanagement"],
  sust: "Ökonomischer Aufstieg mit großen infrastrukturellen und sozialen Herausforderungen.",
  exam: "Tertiärisierung, Offshoring, Wachstumsregion.",
  atlas: "Indien: Wirtschaft, Städte." },
{ id: "stuttgart", name: "Stuttgart: Stadtklima in Kessellage", region: "Baden-Württemberg, Deutschland", lat: 48.78, lon: 9.18, topics: ["stadt_klima"], scale: "lokal",
  facts: ["Innenstadt liegt in einem Talkessel mit geringem Luftaustausch.", "Stadtklimatologie wird dort seit Jahrzehnten in der Planung berücksichtigt.", "Hangwinde und Kaltluftabflüsse sollen über Freiflächen in die Stadt gelangen."],
  causes: ["Relief (Kessellage), Inversionswetterlagen", "Dichte Bebauung, Verkehr"],
  cons: ["Hitzebelastung, Luftschadstoffe", "Planerische Freihaltung von Frischluftschneisen"],
  actors: ["Stadtplanung", "Bauwirtschaft", "Bürgerinnen und Bürger"],
  conflicts: ["Bauland vs. Frischluftschneisen"],
  sol: ["Klimaatlas als Planungsgrundlage", "Dach- und Fassadenbegrünung", "Freihaltung von Hanglagen"],
  sust: "Vorbild für klimaangepasste Planung, Zielkonflikt mit Wohnraumbedarf bleibt.",
  exam: "Stadtklima, Wärmeinsel, Anpassungsstrategien.",
  atlas: "Baden-Württemberg: Relief, Stadtplan Stuttgart." },
{ id: "dharavi", name: "Dharavi in Mumbai", region: "Maharashtra, Indien", lat: 19.04, lon: 72.85, topics: ["metro"], scale: "lokal / regional",
  facts: ["Eine der größten informellen Siedlungen Asiens, zentral in der Megastadt Mumbai gelegen.", "Dichtes Netz kleiner Betriebe (Recycling, Töpferei, Leder, Textil).", "Umstrittene Sanierungspläne seit vielen Jahren."],
  causes: ["Zuwanderung in die Wirtschaftsmetropole", "Wohnungsmangel und hohe Bodenpreise"],
  cons: ["Mangelnde Sanitärversorgung, Gesundheitsrisiken", "Große informelle Wirtschaftskraft und soziale Netze", "Hoher Bodenwert weckt Investoreninteressen"],
  actors: ["Bewohnerinnen und Bewohner", "Kleinunternehmen", "Bundesstaat und Stadt", "Immobilienentwickler", "NGOs"],
  conflicts: ["Sanierung vs. Verdrängung", "Formelle Planung vs. informelle Ökonomie"],
  sol: ["In-situ-Upgrading", "Umsiedlung in Hochhäuser (umstritten)", "Legalisierung von Landrechten"],
  sust: "Hohe soziale und wirtschaftliche Bedeutung; nachhaltige Lösung braucht Beteiligung der Bewohner.",
  exam: "Marginalisierung, informelle Siedlung, Strategien beurteilen.",
  atlas: "Indien: Städte; Stadtplan Mumbai." },
{ id: "lagos", name: "Lagos", region: "Nigeria, Westafrika", lat: 6.52, lon: 3.38, topics: ["metro", "demo"], scale: "regional / national",
  facts: ["Größte Stadt Nigerias und eine der am schnellsten wachsenden Megastädte Afrikas.", "Wirtschafts- und Handelszentrum mit wichtigem Hafen.", "Großer Teil der Bevölkerung arbeitet im informellen Sektor."],
  causes: ["Hohes natürliches Bevölkerungswachstum", "Land-Stadt-Wanderung"],
  cons: ["Verkehrsüberlastung, Wohnungsmangel, Überflutungsrisiken", "Dynamische Tech- und Kreativwirtschaft"],
  actors: ["Bundesstaat Lagos", "Investoren", "Bewohner informeller Siedlungen"],
  conflicts: ["Prestigeprojekte (z. B. Eko Atlantic) vs. Räumungen informeller Siedlungen"],
  sol: ["Nahverkehrsausbau (Bus, Stadtbahn)", "Upgrading-Programme"],
  sust: "Stark wachsend, Planung hinkt hinterher.",
  exam: "Metropolisierung, Demografie, Primatstadt-Diskussion.",
  atlas: "Afrika: Bevölkerung, Städte; Nigeria." },
{ id: "leipzig", name: "Leipzig: von Schrumpfung zu Wachstum", region: "Sachsen, Deutschland", lat: 51.34, lon: 12.37, topics: ["stadt_demo", "stadt_merk"], scale: "lokal",
  facts: ["Nach 1990 starker Bevölkerungsverlust durch Abwanderung und Suburbanisierung, hoher Leerstand.", "Seit den 2000er-Jahren wieder deutliches Wachstum.", "Stadtumbau mit Rückbau, Sanierung und Zwischennutzungen (Wächterhäuser)."],
  causes: ["Deindustrialisierung nach der Wiedervereinigung", "Später: Hochschulen, Ansiedlungen, günstiger Wohnraum, Kulturszene"],
  cons: ["Leerstand und Rückbau, dann steigende Mieten", "Gentrifizierung in beliebten Vierteln"],
  actors: ["Stadtverwaltung", "Wohnungsgesellschaften", "Eigentümer", "Initiativen", "Zuziehende"],
  conflicts: ["Aufwertung vs. bezahlbarer Wohnraum"],
  sol: ["Stadtumbau Ost", "Zwischennutzung", "Sozialer Wohnungsbau, Milieuschutz"],
  sust: "Beispiel für erfolgreiche Anpassung mit neuen sozialen Herausforderungen.",
  exam: "Schrumpfung, Reurbanisierung, Gentrifizierung.",
  atlas: "Deutschland: Bevölkerungsentwicklung." },
{ id: "italien", name: "Nord-Süd-Gefälle in Italien", region: "Italien", lat: 41.9, lon: 12.5, topics: ["disp", "disp_strat"], scale: "regional / national",
  facts: ["Der Mezzogiorno (Süden) liegt bei Einkommen und Beschäftigung deutlich unter dem Norden.", "Jugendarbeitslosigkeit und Abwanderung sind im Süden höher.", "Seit Jahrzehnten Förderung durch Staat und EU."],
  causes: ["Historische Unterschiede (Industrialisierung im Norden)", "Periphere Lage, Infrastrukturdefizite", "Organisierte Kriminalität, Verwaltungsschwächen"],
  cons: ["Binnenwanderung nach Norden und ins Ausland", "Unterschiedliche Lebensqualität"],
  actors: ["Staat, Regionen", "EU (Strukturfonds)", "Unternehmen", "Bevölkerung"],
  conflicts: ["Verteilung von Fördermitteln", "Zentralstaat vs. Regionen"],
  sol: ["EU-Kohäsionspolitik", "Infrastruktur, Sonderwirtschaftszonen im Süden", "Tourismus- und Agrarförderung"],
  sust: "Wirkung der Förderung umstritten; Disparität besteht fort.",
  exam: "Regionale Disparitäten, Strategien auf nationaler/EU-Ebene.",
  atlas: "Italien: Wirtschaft; Europa: BIP je Einwohner nach Regionen." },
{ id: "grameen", name: "Mikrokredite in Bangladesch", region: "Bangladesch, Südasien", lat: 23.7, lon: 90.4, topics: ["disp_strat"], scale: "national / lokal",
  facts: ["Die Grameen Bank vergibt Kleinkredite, überwiegend an Frauen.", "2006 Friedensnobelpreis an Muhammad Yunus und die Grameen Bank.", "Modell wurde weltweit nachgeahmt."],
  causes: ["Kein Zugang armer Menschen zu Bankkrediten"],
  cons: ["Gründung kleiner Unternehmen, Stärkung von Frauen", "Kritik: Überschuldung, teils hohe Zinsen bei anderen Anbietern"],
  actors: ["Kreditnehmerinnen", "Mikrofinanzinstitute", "Staat", "Internationale Geber"],
  conflicts: ["Soziales Ziel vs. kommerzielle Gewinnerwartung"],
  sol: ["Kombination mit Bildung, Spar- und Versicherungsangeboten"],
  sust: "Hilfreiches Instrument, aber kein Allheilmittel gegen Armut.",
  exam: "Bottom-up-Strategie beurteilen.",
  atlas: "Asien: Bevölkerung, Wirtschaft; Bangladesch." },
{ id: "nigeria_japan", name: "Demografie im Vergleich: Nigeria und Japan", region: "Westafrika / Ostasien", lat: 9, lon: 8, topics: ["demo"], scale: "national / global",
  facts: ["Nigeria: sehr junge Bevölkerung, hohe Fertilität, starkes Wachstum.", "Japan: einer der höchsten Anteile über 65-Jähriger weltweit, schrumpfende Bevölkerung."],
  causes: ["Unterschiedliche Phasen des demographischen Übergangs", "Bildung, Urbanisierung, Familienbilder"],
  cons: ["Nigeria: Bedarf an Bildung und Arbeitsplätzen, Chance auf demografische Dividende", "Japan: Fachkräftemangel, Rentenlast, schrumpfende ländliche Räume"],
  actors: ["Regierungen", "Familien", "Unternehmen"],
  conflicts: ["Nigeria: Wachstum vs. Tragfähigkeit", "Japan: Zuwanderung als Lösung umstritten"],
  sol: ["Nigeria: Bildung (v. a. Mädchen), Gesundheitsversorgung", "Japan: Robotik, Pflegeinnovationen, Familienpolitik"],
  sust: "Zwei gegensätzliche Herausforderungen der Tragfähigkeit.",
  exam: "Demographischer Übergang anwenden, Pyramiden vergleichen.",
  atlas: "Welt: Bevölkerungswachstum, Altersstruktur." },
{ id: "frankfurt", name: "Finanzplatz Frankfurt am Main", region: "Hessen, Deutschland", lat: 50.11, lon: 8.68, topics: ["tert"], scale: "regional / global",
  facts: ["Sitz der Europäischen Zentralbank und der Deutschen Bundesbank.", "Wichtigster Börsen- und Bankenstandort Deutschlands.", "Großer internationaler Flughafen als Standortfaktor."],
  causes: ["Historische Handelsstadt", "Verkehrsgunst, Agglomerationsvorteile"],
  cons: ["Hohe Einkommen, starker Dienstleistungssektor", "Hohe Mieten, Pendlerströme"],
  actors: ["Banken, Finanzinstitutionen", "Stadt, Land", "Beschäftigte"],
  conflicts: ["Bürobedarf vs. Wohnraum"],
  sol: ["Umwandlung von Büros in Wohnungen", "ÖPNV-Ausbau in der Region"],
  sust: "Wirtschaftlich stark, sozial-räumlich angespannt.",
  exam: "Tertiärisierung, Global City, Standortfaktoren.",
  atlas: "Hessen / Rhein-Main: Wirtschaft, Verkehr." },
{ id: "mallorca", name: "Mallorca", region: "Balearen, Spanien", lat: 39.6, lon: 2.9, topics: ["tour"], scale: "regional",
  facts: ["Eines der bekanntesten Ziele des Massentourismus in Europa.", "Tourismus ist wichtigster Wirtschaftszweig der Balearen.", "Tourismusabgabe (impuesto de turismo sostenible) seit 2016."],
  causes: ["Klima, Strände, Nähe zu Mitteleuropa, Charterflüge"],
  cons: ["Wohlstand, Arbeitsplätze", "Saisonalität, Wasserknappheit, Wohnungsmangel", "Proteste gegen Overtourism"],
  actors: ["Hotellerie, Reiseveranstalter", "Balearen-Regierung", "Einheimische", "Umweltverbände"],
  conflicts: ["Einnahmen vs. Lebensqualität der Einheimischen"],
  sol: ["Tourismusabgabe", "Regulierung von Ferienwohnungen", "Qualitäts- statt Mengentourismus"],
  sust: "Ökonomisch zentral; ökologische und soziale Belastungsgrenzen erreicht.",
  exam: "Lebenszyklusmodell, Overtourism, Steuerungsinstrumente.",
  atlas: "Spanien: Tourismus, Balearen." },
{ id: "costarica", name: "Ökotourismus in Costa Rica", region: "Mittelamerika", lat: 9.9, lon: -84, topics: ["tour", "disp_strat"], scale: "national",
  facts: ["Rund ein Viertel der Landesfläche steht unter Schutz.", "Ökotourismus ist ein wichtiger Wirtschaftszweig.", "Programm von Zahlungen für Umweltleistungen an Waldbesitzer."],
  causes: ["Große Biodiversität", "Politische Stabilität", "Frühe Naturschutzpolitik"],
  cons: ["Einnahmen und Arbeitsplätze auch im ländlichen Raum", "Wiederbewaldung", "Risiko: Übernutzung beliebter Parks, Flugreisen"],
  actors: ["Staat, Nationalparkbehörde", "Lokale Gemeinden", "Reiseveranstalter", "Touristinnen und Touristen"],
  conflicts: ["Besucherzahlen vs. Schutz"],
  sol: ["Besucherlenkung, Kontingente", "Community-based Tourism"],
  sust: "Oft genanntes Vorbild; Klimabilanz der Anreise bleibt Problem.",
  exam: "Nachhaltiger Tourismus, Vergleich mit Massentourismus.",
  atlas: "Mittelamerika: Physische Karte, Schutzgebiete." }
];
