/* ===== THEMEN (Fokussierungen 2027) · Inhalte sind Übungsmaterial ===== */
/* quiz: [Frage, [Optionen], richtig, Warum richtig, Warum die anderen falsch] */
window.TOPICS = [
{ id: "lw_trop", if: 3, t: "Landwirtschaft in den Tropen und Weltmarkt", short: "Tropen & Weltmarkt",
  goal: "Ich kann Formen tropischer Landwirtschaft unterscheiden und erklären, wie Weltmarktprozesse (Preise, Konzerne, Handelsketten) sie prägen.",
  wissen: ["In den immerfeuchten und wechselfeuchten Tropen stehen sich zwei Systeme gegenüber: Subsistenzwirtschaft (z. B. Wanderfeldbau, Shifting Cultivation, kleinbäuerlicher Mischanbau) und exportorientierte Marktproduktion auf Plantagen oder bei Vertragsbauern (Cash Crops wie Kakao, Kaffee, Bananen, Palmöl, Soja).",
    "Tropische Böden sind oft nährstoffarm (Ferralsole): Die Nährstoffe stecken vor allem in der Biomasse. Nach Rodung sinkt die Fruchtbarkeit schnell – ein Grund für Rotationssysteme und für Düngerbedarf auf Plantagen.",
    "Weltmarktintegration bringt Devisen, Arbeitsplätze und Infrastruktur, aber auch Abhängigkeit von schwankenden Rohstoffpreisen, Landkonflikte (Land Grabbing), Monokulturen und Entwaldung. Wertschöpfung (Verarbeitung, Handel) findet häufig in Industrieländern statt. Instrumente wie Fairer Handel, Zertifizierung (z. B. Bio, RSPO) oder Lieferkettengesetze sollen Standards verbessern."],
  terms: [["Cash Crop", "Für den (Welt-)Markt angebautes Produkt, nicht für den Eigenbedarf."], ["Subsistenzwirtschaft", "Produktion überwiegend für den Eigenbedarf."], ["Plantage", "Landwirtschaftlicher Großbetrieb mit Monokultur, meist exportorientiert."], ["Shifting Cultivation", "Wanderfeldbau: Rodung, Anbau für einige Jahre, dann Brache und Verlagerung."], ["Terms of Trade", "Austauschverhältnis zwischen Export- und Importpreisen eines Landes."], ["Land Grabbing", "Großflächiger Landerwerb durch Investoren, oft zulasten lokaler Nutzer."], ["Wertschöpfungskette", "Abfolge der Produktions- und Verarbeitungsstufen bis zum Endprodukt."], ["Nährstoffkreislauf (kurzgeschlossen)", "Nährstoffe zirkulieren v. a. zwischen Vegetation und Streu, kaum im Boden gespeichert."]],
  vis: "climate_trop", cases: ["palmoel", "kakao"],
  quiz: [
    ["Warum sinkt die Bodenfruchtbarkeit nach Rodung im tropischen Regenwald schnell?", ["Nährstoffe sind vor allem in der Biomasse gespeichert", "Die Temperaturen sind zu niedrig", "Es regnet zu wenig"], 0, "Ferralsole speichern kaum Nährstoffe; mit der Vegetation geht der Nährstoffvorrat verloren.", "Temperatur und Niederschlag sind in den immerfeuchten Tropen hoch – sie sind nicht der begrenzende Faktor."],
    ["Was beschreibt verschlechterte Terms of Trade für ein Kakao-Exportland?", ["Für dieselbe Menge Kakao kann es weniger Importgüter kaufen", "Es exportiert mehr Kakao als früher", "Der Kakao wird im Land verarbeitet"], 0, "Terms of Trade = Verhältnis Export- zu Importpreisen.", "Exportmenge und Verarbeitungsort sind andere Größen."],
    ["Welche Maßnahme erhöht die Wertschöpfung im Anbauland am direktesten?", ["Verarbeitung der Rohware im Land (z. B. Schokoladenproduktion)", "Ausweitung der Anbaufläche", "Senkung der Exportpreise"], 0, "Weiterverarbeitung hält Wertschöpfungsstufen im Land.", "Mehr Fläche erhöht die Menge, nicht den Wert je Tonne; niedrigere Preise senken Einnahmen."]
  ],
  task: { op: "beurteilen", afb: "III", prompt: "Beurteile die Bedeutung der Palmölproduktion für die Entwicklung Indonesiens.", erw: ["Kriterien offenlegen (ökonomisch, sozial, ökologisch)", "Pro: Exporterlöse, Einkommen für Kleinbauern, Infrastruktur", "Contra: Entwaldung, Torfbrände/CO₂, Landkonflikte, Abhängigkeit vom Weltmarktpreis", "Abwägung und begründetes Urteil (z. B. nur mit Zertifizierung/Flächenschutz tragfähig)"] } },

{ id: "lw_int", if: 3, t: "Intensivierung in gemäßigter Zone und Subtropen", short: "Intensivierung",
  goal: "Ich kann Formen intensiver Landwirtschaft (Veredelung, Sonderkulturen, Bewässerung) erklären und ihre Folgen bewerten.",
  wissen: ["Intensivierung bedeutet: mehr Kapital, Technik, Dünger, Futter oder Wasser je Fläche, um den Ertrag zu steigern. Beispiele sind die Veredelungswirtschaft (Tiermast mit importierten Futtermitteln), Gewächshausanbau und Bewässerungsfeldbau in den Subtropen.",
    "Agrobusiness verbindet Produktion, Verarbeitung und Vermarktung (vertikale Integration). Betriebe wachsen, spezialisieren sich und arbeiten eng mit Lebensmittelindustrie und Handel zusammen.",
    "Folgen: hohe Produktivität und günstige Lebensmittel, aber Nitratbelastung im Grundwasser (Gülle), Übernutzung von Grundwasser in Trockenräumen, Bodenversalzung bei Bewässerung, Biodiversitätsverlust, Tierwohl-Debatten und prekäre Arbeitsbedingungen für Saisonkräfte."],
  terms: [["Intensivierung", "Steigerung des Einsatzes von Kapital und Arbeit je Flächeneinheit."], ["Veredelungswirtschaft", "Umwandlung pflanzlicher Futtermittel in tierische Produkte."], ["Agrobusiness", "Verflechtung von Landwirtschaft, vor- und nachgelagerter Industrie und Handel."], ["Vertikale Integration", "Zusammenfassung mehrerer Stufen der Wertschöpfung in einem Unternehmen."], ["Bewässerungsfeldbau", "Anbau mit künstlicher Wasserzufuhr, v. a. in Trockengebieten."], ["Versalzung", "Anreicherung von Salzen im Boden durch Verdunstung von Bewässerungswasser."], ["Nitratbelastung", "Eintrag von Stickstoffverbindungen ins Grundwasser, z. B. durch Gülle."], ["Sonderkultur", "Intensive Kultur mit hohem Arbeits- und Kapitaleinsatz (Gemüse, Obst, Wein)."]],
  vis: "bar_irrig", cases: ["almeria", "oldenburg"],
  quiz: [
    ["Warum führt Bewässerung in Trockengebieten oft zu Bodenversalzung?", ["Das Wasser verdunstet und die gelösten Salze bleiben zurück", "Salz wird als Dünger ausgebracht", "Meerwasser wird direkt genutzt"], 0, "Hohe Verdunstung + kapillarer Aufstieg reichern Salze an.", "Salz als Dünger oder direkte Meerwassernutzung sind nicht die typische Ursache."],
    ["Was kennzeichnet die Veredelungswirtschaft?", ["Tierhaltung auf Basis großer Futtermittelmengen", "Anbau veredelter Obstsorten", "Ökologischer Landbau ohne Tiere"], 0, "Pflanzliche Futtermittel (oft importiertes Soja) werden in Fleisch, Milch, Eier umgewandelt.", "Obstveredelung ist ein gärtnerischer Begriff; ökologischer Landbau ist das Gegenteil intensiver Veredelung."],
    ["Welche Folge ist typisch für intensive Tierhaltung in Nordwestdeutschland?", ["Nitratbelastung des Grundwassers", "Bodenversalzung", "Wüstenbildung"], 0, "Zu viel Gülle je Fläche → Nitrat im Grundwasser.", "Versalzung und Desertifikation betreffen vor allem Trockengebiete."]
  ],
  task: { op: "erörtern", afb: "III", prompt: "Erörtere, ob der Gemüseanbau unter Folie in Almería als nachhaltig gelten kann.", erw: ["Kriterien der Nachhaltigkeit (ökonomisch, ökologisch, sozial)", "Pro: hohe Erträge, Exporte, Wasser-Effizienz durch Tropfbewässerung", "Contra: Grundwasserübernutzung, Plastikmüll, Arbeitsbedingungen von Migrantinnen und Migranten", "Abwägung, Fazit mit Bedingungen (z. B. Entsalzungsanlagen, Recycling, Arbeitsrecht)"] } },

{ id: "lw_nach", if: 3, t: "Ressourcengefährdung und Nachhaltigkeit", short: "Ressourcen & Nachhaltigkeit",
  goal: "Ich kann Ursachen landwirtschaftlicher Ressourcengefährdung (Boden, Wasser, Biodiversität) erklären und Strategien nachhaltiger Landwirtschaft beurteilen.",
  wissen: ["Landwirtschaft nutzt die Ressourcen Boden, Wasser und Biodiversität – und gefährdet sie, wenn sie übernutzt werden: Bodenerosion durch Wind und Wasser, Humusverlust, Verdichtung, Versalzung, Grundwasserabsenkung, Pestizideinträge.",
    "Desertifikation ist die Degradation von Land in Trockengebieten durch Klimaschwankungen und menschliche Übernutzung (Überweidung, Brennholz, falsche Bewässerung). Das Aralsee-Syndrom zeigt, wie Großbewässerung ganze Ökosysteme zerstören kann.",
    "Nachhaltige Ansätze: ökologischer Landbau, Agroforstwirtschaft, konservierende Bodenbearbeitung (Direktsaat, Mulch), Fruchtfolgen, Tröpfchenbewässerung, regionale Vermarktung. Ob sie die wachsende Nachfrage decken können, ist umstritten (Ertrag vs. Umweltwirkung)."],
  terms: [["Bodenerosion", "Abtrag von Bodenmaterial durch Wasser oder Wind."], ["Desertifikation", "Landdegradation in Trockengebieten durch Klima und Übernutzung."], ["Agroforstwirtschaft", "Kombination von Bäumen/Sträuchern mit Ackerbau oder Tierhaltung auf einer Fläche."], ["Konservierende Bodenbearbeitung", "Verzicht auf Pflügen, Mulchauflage, Schutz vor Erosion."], ["Tröpfchenbewässerung", "Wassersparende Bewässerung direkt an der Pflanzenwurzel."], ["Ökologischer Fußabdruck", "Fläche, die zur Deckung eines Lebensstils rechnerisch nötig ist."], ["Virtuelles Wasser", "Wassermenge, die zur Herstellung eines Produkts verbraucht wird."], ["Nachhaltigkeitsdreieck", "Modell mit ökologischer, ökonomischer und sozialer Dimension."]],
  vis: "line_aral", cases: ["aral"],
  quiz: [
    ["Was trug hauptsächlich zum Schrumpfen des Aralsees bei?", ["Die Ableitung der Zuflüsse für die Baumwollbewässerung", "Ein Erdbeben", "Der Bau von Wasserkraftwerken am See"], 0, "Amudarja und Syrdarja wurden seit den 1960er-Jahren massiv für Bewässerung genutzt.", "Erdbeben und Kraftwerke am See sind nicht die Ursache."],
    ["Welche Maßnahme schützt am direktesten vor Wassererosion auf Ackerflächen?", ["Mulchauflage und Direktsaat", "Tiefes Pflügen im Herbst", "Entfernen von Hecken"], 0, "Bodenbedeckung bremst Abfluss und schützt die Oberfläche.", "Pflügen und Heckenrodung legen den Boden frei und fördern Erosion."],
    ["Desertifikation bezeichnet …", ["Landdegradation in Trockengebieten durch Klima und Nutzung", "die natürliche Ausbreitung von Wüsten ohne menschlichen Einfluss", "das Austrocknen von Seen in Europa"], 0, "Die Definition verbindet klimatische und anthropogene Ursachen in Trockengebieten.", "Rein natürliche Wüstenausbreitung oder Seenaustrocknung treffen den Begriff nicht."]
  ],
  task: { op: "erläutern", afb: "II", prompt: "Erläutere das Syndrom der Landdegradation am Beispiel des Aralsees.", erw: ["Ausgangslage: Zuflüsse, Baumwollanbau in der Sowjetunion", "Wirkungskette: Wasserentnahme → Seespiegel sinkt → Salz- und Staubstürme, Fischerei bricht ein", "Folgen für Gesundheit, Klima (kontinentaler), Wirtschaft", "Beispiel/Beleg aus Material oder Atlas"] } },

{ id: "lw_klima", if: 3, t: "Landwirtschaft im Klimawandel", short: "Landwirtschaft & Klima",
  goal: "Ich kann Auswirkungen des Klimawandels auf die Landwirtschaft regional differenziert erklären und Anpassungs- sowie Klimaschutzstrategien bewerten.",
  wissen: ["Der Klimawandel verschiebt Anbaugrenzen: Hitze, Dürre, Starkregen und veränderte Niederschlagsverteilung treffen vor allem Regionen, die ohnehin trocken oder arm sind (z. B. Sahel). In höheren Breiten können Vegetationsperioden länger werden.",
    "Landwirtschaft ist zugleich Verursacherin: Methan aus Rinderhaltung und Reisanbau, Lachgas aus Stickstoffdüngung, CO₂ aus Entwaldung und trockengelegten Mooren.",
    "Anpassung: dürreresistente Sorten, angepasste Fruchtfolgen, Wasserspeicherung, Versicherungen, Frühwarnsysteme. Klimaschutz: Humusaufbau, Wiedervernässung von Mooren, weniger Tierbestände, Agroforst. Programme wie die Große Grüne Mauer in der Sahelzone kombinieren Anpassung und Schutz."],
  terms: [["Anbaugrenze", "Grenze, bis zu der eine Kultur klimatisch sinnvoll angebaut werden kann."], ["Vegetationsperiode", "Zeitraum im Jahr, in dem Pflanzen wachsen können."], ["Dürre", "Längere Phase mit Niederschlagsdefizit und Wassermangel."], ["Anpassung (Adaption)", "Maßnahmen, um Folgen des Klimawandels zu verringern."], ["Klimaschutz (Mitigation)", "Maßnahmen zur Minderung von Treibhausgasemissionen."], ["Methan", "Starkes Treibhausgas, u. a. aus Wiederkäuern und Nassreis."], ["Resilienz", "Fähigkeit eines Systems, Störungen zu verkraften und sich anzupassen."], ["Ernährungssicherheit", "Dauerhafter Zugang aller Menschen zu ausreichender Nahrung."]],
  vis: "climate_sahel", cases: ["sahel"],
  quiz: [
    ["Welcher Unterschied besteht zwischen Anpassung und Klimaschutz?", ["Anpassung mindert Folgen, Klimaschutz mindert Emissionen", "Beide Begriffe bedeuten dasselbe", "Klimaschutz betrifft nur Städte"], 0, "Adaption vs. Mitigation.", "Die Begriffe sind klar unterschieden; Klimaschutz betrifft alle Sektoren."],
    ["Welche landwirtschaftliche Quelle setzt vor allem Methan frei?", ["Rinderhaltung", "Tröpfchenbewässerung", "Obstanbau"], 0, "Wiederkäuer bilden bei der Verdauung Methan.", "Bewässerung und Obstbau sind keine nennenswerten Methanquellen."],
    ["Warum gilt die Sahelzone als besonders verwundbar?", ["Hohe Niederschlagsvariabilität und große Abhängigkeit vom Regenfeldbau", "Weil dort keine Landwirtschaft betrieben wird", "Wegen niedriger Temperaturen"], 0, "Schwankende Regenzeiten treffen Regenfeldbau und Weidewirtschaft direkt.", "Dort wird viel Landwirtschaft betrieben; niedrige Temperaturen sind kein Merkmal."]
  ],
  task: { op: "bewerten", afb: "III", prompt: "Bewerte die Initiative «Große Grüne Mauer» als Strategie gegen Desertifikation im Sahel.", erw: ["Wertmaßstäbe offenlegen (Wirksamkeit, Beteiligung, Kosten, Nachhaltigkeit)", "Pro: Bodenschutz, Einkommen, Klimaschutz, regionale Identifikation", "Contra: schleppende Umsetzung, Finanzierung, Konflikte, Pflege der Bäume", "Urteil mit Bedingungen (lokale Beteiligung, Mosaik statt Baumreihe)"] } },

{ id: "ind_struk", if: 4, t: "Strukturwandel industriell geprägter Räume", short: "Strukturwandel",
  goal: "Ich kann Ursachen, Phasen und Folgen des Strukturwandels altindustrieller Räume erklären und Strategien der Revitalisierung beurteilen.",
  wissen: ["Altindustrielle Räume wie das Ruhrgebiet entstanden durch die harten Standortfaktoren Kohle, Erz, Wasserwege und Arbeitskräfte (Montanindustrie). Mit billiger Importkohle, Globalisierung und Produktivitätssteigerung verloren diese Faktoren an Bedeutung: Kohle- und Stahlkrisen seit den späten 1950er-Jahren.",
    "Folgen: Arbeitsplatzverlust, Abwanderung, Brachflächen, Umweltschäden, Imageprobleme. Der Wandel folgt oft Phasen: Krise → Umstrukturierung → Diversifizierung (Tertiärisierung, Hochschulen, Logistik, Umwelttechnik, Kultur, Tourismus).",
    "Weiche Standortfaktoren (Image, Freizeitwert, Bildung, Kultur) gewinnen an Bedeutung. Beispiele sind die Umnutzung von Industriebrachen (Zeche Zollverein, Landschaftspark Duisburg-Nord) und Innovationsparks. Die Steinkohleförderung im Ruhrgebiet endete 2018."],
  terms: [["Strukturwandel", "Langfristige Veränderung der Wirtschafts- und Beschäftigungsstruktur eines Raumes."], ["Montanindustrie", "Bergbau sowie Eisen- und Stahlindustrie."], ["Harte Standortfaktoren", "Messbare Faktoren wie Rohstoffe, Verkehr, Flächen, Kosten."], ["Weiche Standortfaktoren", "Schwer messbare Faktoren wie Image, Lebensqualität, Kultur."], ["Deindustrialisierung", "Rückgang des Industriesektors an Beschäftigung und Wertschöpfung."], ["Brachfläche", "Ungenutzte, früher meist industriell genutzte Fläche."], ["Revitalisierung", "Wiedernutzung und Aufwertung von Brachen oder Stadtteilen."], ["Diversifizierung", "Verbreiterung der Wirtschaftsstruktur auf viele Branchen."]],
  vis: "line_sectors", cases: ["ruhr"],
  quiz: [
    ["Welcher Faktor löste die Kohlekrise im Ruhrgebiet wesentlich aus?", ["Günstigere Importkohle und Ölkonkurrenz", "Ein Mangel an Arbeitskräften", "Fehlende Verkehrswege"], 0, "Importkohle und Erdöl waren billiger als die Förderung in großer Tiefe.", "Arbeitskräfte und Verkehrswege waren vorhanden – sie waren Gründe für den Aufstieg."],
    ["Welcher ist ein weicher Standortfaktor?", ["Kulturangebot einer Stadt", "Autobahnanschluss", "Grundstückspreis"], 0, "Kultur ist schwer messbar und wirkt über Lebensqualität/Image.", "Autobahn und Preis sind messbare harte Faktoren."],
    ["Revitalisierung einer Zechenbrache bedeutet …", ["Neue Nutzung und Aufwertung der Fläche", "Abriss ohne Nachnutzung", "Wiederaufnahme der Kohleförderung"], 0, "Z. B. Kultur-, Gewerbe- oder Freizeitnutzung.", "Abriss ohne Nutzung oder neue Förderung sind keine Revitalisierung."]
  ],
  task: { op: "analysieren", afb: "II", prompt: "Analysiere den Wandel der Beschäftigtenstruktur einer altindustriellen Stadt anhand der Diagramm-Materialien.", erw: ["Leitfrage und Aspekte (Sektoren, Zeitraum, Tempo)", "Befunde mit Zahlen/Index", "Zusammenhänge: Rückgang II. Sektor, Wachstum III. Sektor", "Zwischenfazit: Tertiärisierung, aber Beschäftigungslücke"] } },

{ id: "ind_wachs", if: 4, t: "Herausbildung von Wachstumsregionen", short: "Wachstumsregionen",
  goal: "Ich kann erklären, warum sich Wachstumsregionen herausbilden (Cluster, Innovation, Netzwerke) und ihre Chancen und Risiken bewerten.",
  wissen: ["Wachstumsregionen verzeichnen überdurchschnittliches Wachstum bei Beschäftigung, Einkommen und Innovation. Beispiele: Silicon Valley, Shenzhen (Sonderwirtschaftszone seit 1980), Großraum München.",
    "Erklärungsansätze: Clusterbildung (räumliche Konzentration verbundener Unternehmen, Zulieferer, Forschung), Agglomerationsvorteile (Fühlungsvorteile, qualifizierte Arbeitskräfte), Netzwerke und Wissenstransfer, staatliche Förderung, Risikokapital.",
    "Kumulative Prozesse verstärken Wachstum (Modell der zirkulären Verursachung nach Myrdal): Erfolg zieht Kapital und Talente an. Kehrseiten: Wohnungsknappheit, Verkehrsüberlastung, soziale Spaltung, Abhängigkeit von einer Branche sowie Entzugseffekte in peripheren Räumen."],
  terms: [["Cluster", "Räumliche Konzentration verbundener Unternehmen und Institutionen einer Branche."], ["Agglomerationsvorteile", "Vorteile durch räumliche Nähe vieler Betriebe (Arbeitsmarkt, Zulieferer, Wissen)."], ["Fühlungsvorteil", "Vorteil durch persönliche Kontakte und schnellen Informationsaustausch."], ["Sonderwirtschaftszone", "Gebiet mit besonderen wirtschaftlichen Regeln (Steuern, Zölle) zur Investitionsförderung."], ["High-Tech-Branche", "Forschungsintensive Branche (IT, Biotech, Mikroelektronik)."], ["Kumulative Verursachung", "Sich selbst verstärkender Wachstums- oder Schrumpfungsprozess."], ["Spillover-Effekt", "Übertragung von Wissen oder Wachstum auf andere Unternehmen/Räume."], ["Backwash-Effekt", "Entzug von Kapital und Arbeitskräften aus peripheren Räumen."]],
  vis: "scatter_regions", cases: ["shenzhen"],
  quiz: [
    ["Was ist ein Cluster?", ["Räumliche Konzentration verbundener Unternehmen und Forschung", "Ein einzelner Großkonzern", "Ein Gewerbegebiet ohne Verbindung der Betriebe"], 0, "Entscheidend ist die Verflechtung, nicht nur die Nähe.", "Ein Konzern allein oder unverbundene Betriebe bilden kein Cluster."],
    ["Welcher Effekt beschreibt den Abzug von Arbeitskräften aus peripheren Räumen in Wachstumszentren?", ["Backwash-Effekt", "Spillover-Effekt", "Multiplikatoreffekt"], 0, "Backwash = Entzugseffekt.", "Spillover beschreibt positive Ausbreitung; Multiplikator die Vervielfachung von Wirkungen."],
    ["Warum wuchs Shenzhen ab 1980 besonders schnell?", ["Sonderwirtschaftszone mit Investitionsanreizen nahe Hongkong", "Große Kohlevorkommen", "Isolierte Lage"], 0, "Sonderrechte, günstige Arbeitskräfte und Nähe zu Hongkong zogen Kapital an.", "Kohle und Isolation waren keine Wachstumsfaktoren."]
  ],
  task: { op: "überprüfen", afb: "III", prompt: "Überprüfe die These: «Wachstumsregionen entstehen vor allem durch staatliche Förderung.»", erw: ["These und Prüfkriterien", "Belege für staatliche Rolle (Sonderwirtschaftszone, Forschungsförderung)", "Gegenbelege: Cluster, Unternehmertum, Kapital, Hochschulen", "Ergebnis: These teilweise bestätigt / eingeschränkt"] } },

{ id: "digital", if: 4, t: "Digitalisierung und Raumstrukturen", short: "Digitalisierung",
  goal: "Ich kann erklären, wie digitale Infrastruktur, Onlinehandel und mobiles Arbeiten Standorte, Verkehre und Pendlerströme verändern.",
  wissen: ["Digitale Infrastruktur (Glasfaser, Mobilfunk, Rechenzentren) wird zum harten Standortfaktor. Regionen ohne schnelles Internet verlieren an Attraktivität für Betriebe und Haushalte (digitale Kluft).",
    "Onlinehandel verlagert Umsätze aus den Innenstädten: Leerstand im stationären Einzelhandel, gleichzeitig entstehen große Logistikzentren an Autobahnknoten und mehr Lieferverkehr auf der «letzten Meile».",
    "Homeoffice und digitale Arbeit verändern Pendlerströme: weniger tägliche Wege, dafür teils längere Distanzen zwischen Wohn- und Arbeitsort; Nachfrage nach Wohnraum im Umland; Coworking-Spaces. Arbeitsplätze können auch international verlagert werden (Offshoring von Dienstleistungen)."],
  terms: [["Digitale Infrastruktur", "Netze und Anlagen für Datenübertragung und -speicherung."], ["Digitale Kluft", "Ungleicher Zugang zu digitaler Infrastruktur zwischen Räumen oder Gruppen."], ["Onlinehandel (E-Commerce)", "Verkauf von Waren und Dienstleistungen über das Internet."], ["Letzte Meile", "Letzter Abschnitt der Lieferkette bis zur Haustür."], ["Logistikzentrum", "Großflächiger Standort für Lagerung, Kommissionierung und Versand."], ["Pendlerstrom", "Regelmäßige Bewegung zwischen Wohn- und Arbeitsort."], ["Homeoffice", "Arbeit von zu Hause mithilfe digitaler Technik."], ["Offshoring", "Verlagerung von Unternehmensfunktionen ins Ausland."]],
  vis: "map_flows", cases: ["innenstadt", "bengaluru"],
  quiz: [
    ["Wo entstehen große Logistikzentren des Onlinehandels bevorzugt?", ["An Autobahnknoten mit großen, günstigen Flächen", "In historischen Altstädten", "In Naturschutzgebieten"], 0, "Erreichbarkeit und Fläche sind entscheidend.", "Altstädte sind eng und teuer; Schutzgebiete sind nicht bebaubar."],
    ["Welche Wirkung hat verbreitetes Homeoffice typischerweise auf Pendlerströme?", ["Weniger tägliche Pendelwege, teils größere Distanzen", "Mehr tägliche Pendelwege", "Keine Veränderung"], 0, "Seltener pendeln erlaubt weiter entfernte Wohnorte.", "Mehr Wege widerspricht dem Prinzip; «keine Veränderung» ignoriert die belegte Verschiebung."],
    ["Die digitale Kluft beschreibt …", ["ungleichen Zugang zu digitaler Infrastruktur", "den Abstand zwischen zwei Rechenzentren", "den Preis für Smartphones"], 0, "Räumliche/soziale Ungleichheit beim Zugang.", "Die anderen Optionen sind keine Fachbedeutung."]
  ],
  task: { op: "analysieren", afb: "II", prompt: "Analysiere anhand der Karte die Veränderung der Pendlerströme in der Modellregion nach Einführung von Homeoffice-Regelungen.", erw: ["Aspekte: Richtung, Stärke, Distanz der Ströme", "Befunde aus Karte (Pfeilstärken, Legende)", "Zusammenhang mit Digitalisierung/Wohnkosten", "Zwischenfazit"] } },

{ id: "stadt_merk", if: 5, t: "Merkmale, innere Differenzierung und Wandel von Städten", short: "Stadtstrukturen",
  goal: "Ich kann Stadtstrukturen mit Stadtmodellen beschreiben, erklären und Prozesse wie Suburbanisierung, Gentrifizierung und Reurbanisierung einordnen.",
  wissen: ["Städte gliedern sich in funktional und sozial unterschiedliche Viertel. Stadtmodelle (konzentrische Ringe, Sektoren, Mehrkerne) und kulturraumspezifische Modelle (europäische, nordamerikanische, lateinamerikanische, orientalische Stadt) helfen beim Einordnen.",
    "Prozesse: Suburbanisierung (Verlagerung von Wohnen, Handel, Gewerbe ins Umland), Reurbanisierung (Rückkehr in die Kernstadt), Gentrifizierung (Aufwertung eines Viertels mit Verdrängung einkommensschwächerer Gruppen), Segregation (räumliche Trennung sozialer Gruppen).",
    "Die europäische Stadt ist gekennzeichnet durch einen historischen Kern, hohe Dichte, Mischnutzung und öffentlichen Nahverkehr. Leitbilder wandeln sich von der funktionsgetrennten zur kompakten, durchmischten «Stadt der kurzen Wege»."],
  terms: [["Suburbanisierung", "Verlagerung von Bevölkerung und Funktionen ins städtische Umland."], ["Reurbanisierung", "Wiederzunahme von Bevölkerung in der Kernstadt."], ["Gentrifizierung", "Aufwertung eines Stadtviertels mit Verdrängung ansässiger Bewohner."], ["Segregation", "Räumliche Trennung von Bevölkerungsgruppen."], ["CBD", "Central Business District, Hauptgeschäftsbereich einer Stadt."], ["Stadtmodell", "Vereinfachte Darstellung typischer Stadtstrukturen."], ["Mischnutzung", "Wohnen, Arbeiten und Versorgung in räumlicher Nähe."], ["Stadt der kurzen Wege", "Leitbild einer dichten, durchmischten Stadt mit kurzen Distanzen."]],
  vis: "map_city", cases: ["leipzig"],
  quiz: [
    ["Was kennzeichnet Gentrifizierung?", ["Aufwertung eines Viertels mit Verdrängung bisheriger Bewohner", "Abwanderung ins Umland", "Rückgang der Bevölkerung einer Stadt"], 0, "Pioniere → Investitionen → Mietsteigerung → Verdrängung.", "Abwanderung ins Umland = Suburbanisierung; Rückgang = Schrumpfung."],
    ["Welches Merkmal passt zur europäischen Stadt?", ["Historischer Kern mit hoher Dichte", "Schachbrettartige Hochhaus-Downtown", "Ausgedehnte Gated Communities als Regelfall"], 0, "Altstadtkern, Kirche/Markt, dichte Bebauung.", "Downtown-Raster ist nordamerikanisch; Gated Communities prägen eher latein- und nordamerikanische Städte."],
    ["Suburbanisierung wird vor allem gefördert durch …", ["steigende Mobilität und günstigeren Wohnraum im Umland", "sinkende Bodenpreise im Zentrum", "Abbau von Straßen"], 0, "Pkw-Verbreitung und Eigenheimwunsch.", "Sinkende Zentrumspreise und weniger Straßen wirken eher entgegen."]
  ],
  task: { op: "einordnen / zuordnen", afb: "II", prompt: "Ordne die Viertel der Modellstadt auf der Karte den Zonen eines Stadtstrukturmodells zu und begründe.", erw: ["Modell benennen", "Merkmale der Viertel (Nutzung, Dichte, Lage)", "Zuordnung mit Begründung", "Abweichungen vom Modell"] } },

{ id: "stadt_klima", if: 5, t: "Stadtentwicklung im Kontext des Klimawandels", short: "Stadt & Klima",
  goal: "Ich kann erklären, wie der Klimawandel städtische Räume betrifft (Hitze, Starkregen), und Anpassungsstrategien bewerten.",
  wissen: ["Städte bilden Wärmeinseln: Versiegelung, dunkle Oberflächen, Abwärme und fehlende Verdunstung erwärmen die Innenstadt – nachts oft mehrere Grad gegenüber dem Umland. Mit häufigeren Hitzewellen steigt der Hitzestress, besonders für ältere und kranke Menschen.",
    "Starkregen trifft versiegelte Flächen: Das Wasser fließt schnell ab, die Kanalisation läuft über, es drohen urbane Sturzfluten.",
    "Anpassung: blaue und grüne Infrastruktur (Parks, Dach- und Fassadenbegrünung, Wasserflächen), Frischluftschneisen, helle Oberflächen, Entsiegelung, Retentionsflächen und das Prinzip der Schwammstadt. Klimaschutz: ÖPNV, Rad, Energieeffizienz. Zielkonflikt: Nachverdichtung für Wohnraum vs. Freiflächen fürs Klima."],
  terms: [["Stadtklima", "Durch Bebauung verändertes Lokalklima einer Stadt."], ["Wärmeinsel", "Überwärmung der Stadt gegenüber dem Umland."], ["Versiegelung", "Abdichtung des Bodens durch Bebauung und Beläge."], ["Retention", "Rückhalt von Niederschlagswasser."], ["Schwammstadt", "Stadtkonzept, das Regenwasser speichert statt ableitet."], ["Frischluftschneise", "Freifläche, über die kühlere Luft in die Stadt strömt."], ["Anpassungsstrategie", "Planerischer Ansatz zur Verringerung von Klimafolgen."], ["Resilienz", "Widerstands- und Anpassungsfähigkeit gegenüber Störungen."]],
  vis: "map_heat", cases: ["stuttgart"],
  quiz: [
    ["Warum ist es nachts in der Innenstadt oft wärmer als im Umland?", ["Gebäude und Beläge speichern Wärme und geben sie nachts ab", "Die Sonne scheint dort länger", "Es gibt mehr Wind"], 0, "Wärmespeicher + fehlende Verdunstung + Abwärme.", "Sonnenscheindauer ist gleich; mehr Wind würde eher kühlen."],
    ["Was ist das Ziel einer Schwammstadt?", ["Regenwasser vor Ort speichern und verdunsten lassen", "Mehr Kanalrohre bauen", "Alle Flächen versiegeln"], 0, "Speichern entlastet die Kanalisation und kühlt.", "Größere Rohre leiten nur ab; Versiegelung verschärft das Problem."],
    ["Welcher Zielkonflikt ist typisch?", ["Nachverdichtung für Wohnraum vs. Grünflächen fürs Stadtklima", "Mehr Parks vs. bessere Luft", "Radwege vs. Klimaschutz"], 0, "Bauland und Freiflächen konkurrieren.", "Parks und saubere Luft ergänzen sich; Radwege dienen dem Klimaschutz."]
  ],
  task: { op: "bewerten", afb: "III", prompt: "Bewerte die vorgeschlagenen Anpassungsmaßnahmen für die Innenstadt der Modellstadt (Karte Wärmeinsel, Tabelle Kosten/Wirkung).", erw: ["Wertmaßstäbe (Wirkung, Kosten, Zeit, soziale Gerechtigkeit)", "Maßnahmen einzeln abwägen (Begrünung, Entsiegelung, Frischluftschneise)", "Belege aus Karte/Tabelle", "Begründetes Gesamturteil mit Prioritäten"] } },

{ id: "metro", if: 5, t: "Metropolisierung und Marginalisierung", short: "Metropolisierung",
  goal: "Ich kann weltweite Verstädterung, Metropolisierung und Marginalisierung erklären und Strategien für informelle Siedlungen beurteilen.",
  wissen: ["Seit 2007 lebt mehr als die Hälfte der Weltbevölkerung in Städten. Besonders stark wachsen Städte in Afrika und Asien. Metropolisierung bezeichnet die Konzentration von Bevölkerung, Wirtschaft und Macht in wenigen großen Städten; eine Primatstadt dominiert das Städtesystem eines Landes.",
    "Ursachen: Land-Stadt-Wanderung (Push-Faktoren wie Armut, Landknappheit; Pull-Faktoren wie Jobs, Bildung, Gesundheit) und natürliches Bevölkerungswachstum.",
    "Marginalisierung: Viele Zuwandernde finden nur im informellen Sektor Arbeit und wohnen in informellen Siedlungen (Slums, Favelas) ohne gesicherte Rechte und Infrastruktur. Strategien: Upgrading vor Ort, Legalisierung von Landrechten, Sites-and-Services, sozialer Wohnungsbau – statt Räumung."],
  terms: [["Verstädterung", "Zunahme des Anteils der Stadtbevölkerung an der Gesamtbevölkerung."], ["Metropolisierung", "Konzentration von Bevölkerung und Funktionen in großen Städten."], ["Megastadt", "Stadt mit mehr als 10 Millionen Einwohnern."], ["Primatstadt", "Stadt, die das Städtesystem eines Landes stark dominiert."], ["Marginalisierung", "Soziale und räumliche Ausgrenzung von Bevölkerungsgruppen."], ["Informelle Siedlung", "Siedlung ohne rechtliche Absicherung und ausreichende Infrastruktur."], ["Informeller Sektor", "Wirtschaftliche Tätigkeiten ohne Registrierung, Steuern und soziale Absicherung."], ["Slum-Upgrading", "Verbesserung informeller Siedlungen vor Ort."]],
  vis: "bar_urban", cases: ["dharavi", "lagos"],
  quiz: [
    ["Was ist eine Primatstadt?", ["Eine Stadt, die das Städtesystem ihres Landes dominiert", "Die älteste Stadt eines Landes", "Eine Stadt mit über 10 Mio. Einwohnern"], 0, "Übermäßige Bedeutung im Vergleich zur zweitgrößten Stadt.", "Alter oder Megastadt-Grenze definieren keine Primatstadt."],
    ["Welcher ist ein Pull-Faktor der Land-Stadt-Wanderung?", ["Bessere Bildungs- und Gesundheitsangebote in der Stadt", "Dürre auf dem Land", "Landknappheit"], 0, "Pull = Anziehung am Zielort.", "Dürre und Landknappheit sind Push-Faktoren."],
    ["Warum gilt Upgrading oft als besser als Räumung?", ["Soziale Netze und Arbeitsplätze bleiben erhalten", "Es ist immer kostenlos", "Es verhindert jede Zuwanderung"], 0, "Menschen bleiben nah an Jobs und Netzwerken.", "Upgrading kostet Geld und stoppt Zuwanderung nicht."]
  ],
  task: { op: "erläutern", afb: "II", prompt: "Erläutere Ursachen und Folgen der Marginalisierung am Beispiel einer Megastadt des Globalen Südens.", erw: ["Ursachen (Push/Pull, Bevölkerungswachstum)", "Merkmale informeller Siedlungen und des informellen Sektors", "Folgen (Gesundheit, Infrastruktur, Umwelt, Chancen)", "Konkretes Beispiel mit Belegen"] } },

{ id: "stadt_demo", if: 5, t: "Demografischer und sozialer Wandel in der Stadt", short: "Stadt & Demografie",
  goal: "Ich kann erklären, wie Alterung, Schrumpfung, Zuwanderung und soziale Polarisierung Städte verändern, und Konzepte zukunftsorientierter Stadtentwicklung beurteilen.",
  wissen: ["In Deutschland altert die Bevölkerung; manche Städte schrumpfen (v. a. strukturschwache Regionen), andere wachsen durch Zuwanderung (Schwarmstädte). Beides stellt Anforderungen an Wohnungen, Infrastruktur und soziale Einrichtungen.",
    "Schrumpfung bedeutet Leerstand, unterausgelastete Infrastruktur (Leitungen, Schulen) und sinkende Einnahmen – Antworten sind Stadtumbau, Rückbau und Aufwertung. Wachstum bedeutet Wohnungsknappheit, steigende Mieten und Nutzungskonkurrenz.",
    "Zukunftsorientierte Stadtentwicklung setzt auf Barrierefreiheit, generationengerechtes Wohnen, soziale Durchmischung, integrierte Quartiersentwicklung und Bürgerbeteiligung."],
  terms: [["Demografischer Wandel", "Veränderung von Größe und Altersstruktur einer Bevölkerung."], ["Schrumpfende Stadt", "Stadt mit dauerhaftem Bevölkerungsrückgang."], ["Schwarmstadt", "Stadt, in die viele junge Menschen zuziehen."], ["Stadtumbau", "Anpassung der Stadtstruktur an veränderte Bedarfe (Rückbau, Aufwertung)."], ["Leerstand", "Nicht genutzter Wohn- oder Gewerberaum."], ["Soziale Polarisierung", "Auseinanderdriften von Einkommens- und Lebenslagen."], ["Barrierefreiheit", "Gestaltung, die allen Menschen Nutzung ohne Hindernisse erlaubt."], ["Quartiersmanagement", "Koordinierte Entwicklung eines Stadtviertels mit Bewohnern."]],
  vis: "pyramid_de", cases: ["leipzig"],
  quiz: [
    ["Welches Problem ist typisch für schrumpfende Städte?", ["Unterausgelastete Infrastruktur und Leerstand", "Stark steigende Mieten", "Mangel an Bauland"], 0, "Weniger Nutzer → höhere Kosten je Kopf.", "Mieten- und Baulandknappheit sind Probleme wachsender Städte."],
    ["Was ist eine Schwarmstadt?", ["Eine Stadt mit starkem Zuzug junger Menschen", "Eine Stadt mit vielen Bienenvölkern", "Eine Stadt ohne Zuwanderung"], 0, "Junge Menschen «schwärmen» in wenige attraktive Städte.", "Die anderen Optionen treffen den Fachbegriff nicht."],
    ["Welche Maßnahme passt zur alternden Stadtgesellschaft?", ["Barrierefreie Wohnungen und Wege", "Rückbau aller Bushaltestellen", "Schließung von Arztpraxen"], 0, "Mobilität und Teilhabe älterer Menschen sichern.", "Die anderen Maßnahmen verschlechtern die Versorgung."]
  ],
  task: { op: "erörtern", afb: "III", prompt: "Erörtere, ob der Rückbau von Wohnungen eine geeignete Strategie für eine schrumpfende Stadt ist.", erw: ["Problem und Kontext", "Pro: Leerstand senken, Marktstabilisierung, Freiraum", "Contra: Kosten, Identitätsverlust, künftiger Bedarf", "Abwägung und Fazit (z. B. Rückbau am Rand, Aufwertung im Kern)"] } },

{ id: "disp", if: 6, t: "Merkmale und Ursachen räumlicher Disparitäten", short: "Disparitäten",
  goal: "Ich kann Disparitäten mit Indikatoren messen, auf verschiedenen Maßstabsebenen beschreiben und Ursachen erklären.",
  wissen: ["Disparitäten sind Ungleichheiten der Lebensbedingungen zwischen Räumen – regional (z. B. Nord- und Süditalien), national und global. Gemessen werden sie mit Indikatoren: BNE pro Kopf (in Kaufkraftparitäten), Human Development Index (Lebenserwartung, Bildung, Einkommen), Gini-Koeffizient, Kindersterblichkeit, Zugang zu Wasser.",
    "Erklärungsansätze: Modernisierungstheorie (Entwicklungsrückstand durch fehlende Modernisierung), Dependenztheorie (Abhängigkeit vom Zentrum), Zentrum-Peripherie-Modelle, naturräumliche Faktoren (Binnenlage, Klima, Krankheiten), Governance (Institutionen, Korruption), historische Faktoren (Kolonialismus).",
    "Einzelne Indikatoren verdecken Unterschiede innerhalb eines Landes – daher mehrdimensionale Indizes und kleinräumige Daten nutzen."],
  terms: [["Disparität", "Ungleichheit der Lebensbedingungen zwischen Räumen."], ["Indikator", "Messgröße, die einen Sachverhalt anzeigt."], ["HDI", "Human Development Index: Lebenserwartung, Bildung, Einkommen."], ["Kaufkraftparität (KKP)", "Umrechnung, die Preisunterschiede zwischen Ländern berücksichtigt."], ["Gini-Koeffizient", "Maß der Einkommensungleichheit (0 = gleich, 1 = maximal ungleich)."], ["Zentrum-Peripherie", "Gegensatz zwischen wirtschaftlichem Kernraum und abhängigen Randräumen."], ["Dependenztheorie", "Erklärt Unterentwicklung durch Abhängigkeit von Industrieländern."], ["Modernisierungstheorie", "Erklärt Entwicklung als Nachholen von Modernisierungsschritten."]],
  vis: "choropleth", cases: ["italien"],
  quiz: [
    ["Welche drei Dimensionen fasst der HDI zusammen?", ["Lebenserwartung, Bildung, Einkommen", "Einkommen, Export, Industrie", "Bevölkerungsdichte, Fläche, Klima"], 0, "Das ist die Definition des HDI.", "Export, Industrie oder Fläche sind nicht enthalten."],
    ["Warum rechnet man BNE in Kaufkraftparitäten?", ["Um Preisunterschiede zwischen Ländern auszugleichen", "Um Wechselkurse zu erhöhen", "Um die Bevölkerung zu zählen"], 0, "Ein Dollar kauft in verschiedenen Ländern unterschiedlich viel.", "Die anderen Optionen beschreiben keinen Zweck der KKP."],
    ["Ein Gini-Koeffizient nahe 1 bedeutet …", ["sehr ungleiche Einkommensverteilung", "sehr gleiche Verteilung", "hohes Durchschnittseinkommen"], 0, "1 = maximale Ungleichheit.", "0 wäre gleich; der Gini sagt nichts über die Höhe aus."]
  ],
  task: { op: "vergleichen", afb: "II", prompt: "Vergleiche die Entwicklungsstände der Regionen A und B der Modellkarte anhand geeigneter Indikatoren.", erw: ["Vergleichskriterien (Einkommen, HDI-Werte, Infrastruktur)", "Gemeinsamkeiten", "Unterschiede mit Werten aus der Karte", "Ergebnis des Vergleichs"] } },

{ id: "demo", if: 6, t: "Demografische Prozesse und Tragfähigkeit", short: "Demografie & Tragfähigkeit",
  goal: "Ich kann das Modell des demographischen Übergangs anwenden, Bevölkerungspyramiden auswerten und die Tragfähigkeit von Räumen beurteilen.",
  wissen: ["Das Modell des demographischen Übergangs beschreibt den Wandel von hohen zu niedrigen Geburten- und Sterberaten in fünf Phasen. Weil die Sterberate zuerst sinkt, wächst die Bevölkerung in der Übergangsphase stark.",
    "Bevölkerungspyramiden zeigen die Altersstruktur: Pyramide (junge, wachsende Bevölkerung), Glocke (stabil), Urne (alternd, schrumpfend). Migration verändert die Struktur zusätzlich.",
    "Tragfähigkeit ist die Zahl der Menschen, die ein Raum bei gegebenem Stand von Technik, Wirtschaft und Konsum dauerhaft versorgen kann. Sie hängt nicht nur von Natur, sondern auch von Handel, Innovation und Lebensstil ab. Chancen der demografischen Dividende bestehen, wenn viele Menschen im erwerbsfähigen Alter Arbeit finden."],
  terms: [["Demographischer Übergang", "Modell des Wandels von hohen zu niedrigen Geburten- und Sterberaten."], ["Geburtenrate", "Lebendgeborene je 1.000 Einwohner und Jahr."], ["Fertilitätsrate", "Durchschnittliche Kinderzahl je Frau."], ["Natürliche Wachstumsrate", "Geburtenrate minus Sterberate."], ["Bevölkerungspyramide", "Diagramm der Alters- und Geschlechterstruktur."], ["Tragfähigkeit", "Maximale Bevölkerung, die ein Raum dauerhaft versorgen kann."], ["Demografische Dividende", "Wachstumschance durch hohen Anteil Erwerbsfähiger."], ["Überalterung", "Hoher Anteil älterer Menschen an der Bevölkerung."]],
  vis: "pyramid_ng", cases: ["nigeria_japan"],
  quiz: [
    ["Warum wächst die Bevölkerung in Phase 2/3 des demographischen Übergangs stark?", ["Die Sterberate sinkt früher als die Geburtenrate", "Die Geburtenrate steigt stark", "Es wandern viele Menschen ein"], 0, "Medizin/Hygiene senken zuerst die Sterblichkeit.", "Geburtenrate steigt im Modell nicht; Migration ist nicht Teil des Grundmodells."],
    ["Welche Pyramidenform zeigt eine alternde, schrumpfende Bevölkerung?", ["Urne", "Pyramide", "Glocke"], 0, "Schmale Basis, breite mittlere/obere Altersgruppen.", "Pyramide = junge, wachsende; Glocke = stabile Bevölkerung."],
    ["Tragfähigkeit hängt ab von …", ["Naturraum, Technik, Wirtschaft und Konsum", "nur der Fläche", "nur der Einwohnerzahl"], 0, "Sie ist ein dynamisches Konzept.", "Fläche oder Einwohnerzahl allein bestimmen sie nicht."]
  ],
  task: { op: "anwenden", afb: "II", prompt: "Wende das Modell des demographischen Übergangs auf die Bevölkerungsdaten des Beispiellands an.", erw: ["Modell kurz erläutern", "Daten (Geburten-, Sterberate, Pyramide) einordnen", "Phase bestimmen und begründen", "Grenzen des Modells (Migration, Politik)"] } },

{ id: "disp_strat", if: 6, t: "Strategien zur Reduzierung von Disparitäten", short: "Entwicklungsstrategien",
  goal: "Ich kann Strategien und Instrumente zur Reduzierung regionaler, nationaler und globaler Disparitäten erklären und ihre Wirksamkeit beurteilen.",
  wissen: ["Strategien reichen von Top-down (staatliche Großprojekte, Wachstumspole) bis Bottom-up (lokale Initiativen, Grundbedürfnisse, Partizipation). Regional: Förderung strukturschwacher Räume (in der EU z. B. durch Kohäsions- und Strukturfonds), Infrastruktur, Bildung.",
    "Global: Entwicklungszusammenarbeit, Schuldenerlass, fairer Handel, ausländische Direktinvestitionen, Rücküberweisungen von Migrantinnen und Migranten, Mikrokredite (z. B. Grameen Bank in Bangladesch). Die Agenda 2030 mit 17 Nachhaltigkeitszielen (SDGs) bildet den internationalen Rahmen.",
    "Die Wirksamkeit hängt von Governance, Beteiligung der Bevölkerung, Nachhaltigkeit und Kontext ab. Kritik gibt es an Abhängigkeiten, Korruption und Maßnahmen ohne lokale Verankerung."],
  terms: [["Top-down-Strategie", "Von zentralen Institutionen geplante Entwicklung."], ["Bottom-up-Strategie", "Von lokalen Akteuren ausgehende Entwicklung."], ["Wachstumspol", "Gefördertes Zentrum, von dem Entwicklung ausstrahlen soll."], ["Kohäsionspolitik", "EU-Politik zum Abbau regionaler Unterschiede."], ["Mikrokredit", "Kleinkredit für Menschen ohne Zugang zu Banken."], ["Rücküberweisungen", "Geldtransfers von Migrierten an Familien im Herkunftsland."], ["SDGs", "17 Nachhaltigkeitsziele der Agenda 2030 der Vereinten Nationen."], ["Good Governance", "Verantwortungsvolle, transparente Regierungsführung."]],
  vis: "bar_sdg", cases: ["grameen", "italien"],
  quiz: [
    ["Was kennzeichnet eine Bottom-up-Strategie?", ["Entwicklung geht von lokalen Akteuren aus", "Ein Ministerium plant ein Großprojekt", "Ein ausländischer Konzern baut eine Fabrik"], 0, "Beteiligung vor Ort steht im Mittelpunkt.", "Ministerium und Großprojekt sind Top-down; Konzernansiedlung ist ausländische Investition."],
    ["Wofür steht die Grameen Bank?", ["Mikrokredite für Menschen ohne Bankzugang", "Staatliche Stahlindustrie", "Rohstoffexport"], 0, "Gegründet in Bangladesch, Friedensnobelpreis 2006 an Muhammad Yunus und die Bank.", "Die anderen Optionen passen nicht."],
    ["Warum ist die Wachstumspol-Strategie umstritten?", ["Ausbreitungseffekte bleiben oft aus, Entzugseffekte überwiegen", "Sie ist zu billig", "Sie fördert nur Landwirtschaft"], 0, "Die erhofften Spillover-Effekte treten häufig nicht ein.", "Kosten und Agrarfokus sind nicht der Kritikpunkt."]
  ],
  task: { op: "beurteilen", afb: "III", prompt: "Beurteile die Eignung von Mikrokrediten zur Verringerung von Armut.", erw: ["Kriterien (Reichweite, Einkommenswirkung, Frauenförderung, Risiken)", "Pro: Zugang zu Kapital, Selbstständigkeit, Empowerment", "Contra: Überschuldung, hohe Zinsen, geringe Wirkung ohne Markt/Infrastruktur", "Differenziertes Urteil"] } },

{ id: "tert", if: 7, t: "Tertiärisierung von Wirtschaft und Beschäftigung", short: "Tertiärisierung",
  goal: "Ich kann den sektoralen Wandel (Drei-Sektoren-Modell) erklären, Dienstleistungsarten unterscheiden und Standortmuster des Tertiärsektors analysieren.",
  wissen: ["Nach dem Drei-Sektoren-Modell (Fourastié) verlagert sich die Beschäftigung mit steigender Entwicklung vom primären (Landwirtschaft) über den sekundären (Industrie) zum tertiären Sektor (Dienstleistungen). In Deutschland arbeiten heute rund drei Viertel der Erwerbstätigen im Dienstleistungssektor.",
    "Dienstleistungen sind vielfältig: distributive (Handel, Verkehr), unternehmensorientierte bzw. wissensintensive (Beratung, IT, Finanzen), konsumorientierte (Gastronomie, Freizeit) und öffentliche (Bildung, Gesundheit). Manche Autorinnen und Autoren grenzen einen quartären Informationssektor ab.",
    "Hochwertige Dienstleistungen konzentrieren sich in Metropolen (Global Cities wie London, New York, Frankfurt als Finanzplatz). Digitalisierung erlaubt zugleich die Auslagerung standardisierter Dienstleistungen (Callcenter, IT-Service) in Länder mit niedrigeren Löhnen, z. B. nach Indien."],
  terms: [["Tertiärisierung", "Zunahme der Dienstleistungen an Beschäftigung und Wertschöpfung."], ["Drei-Sektoren-Modell", "Modell des sektoralen Wandels nach Fourastié."], ["Unternehmensorientierte Dienstleistungen", "Dienstleistungen für Firmen, z. B. Beratung, IT, Werbung."], ["Global City", "Stadt mit weltweiten Steuerungsfunktionen in Finanzen und Wirtschaft."], ["Wissensökonomie", "Wirtschaft, in der Wissen der zentrale Produktionsfaktor ist."], ["Quartärer Sektor", "Informations- und Wissensdienstleistungen (teils eigener Sektor)."], ["Outsourcing", "Auslagerung von Aufgaben an externe Anbieter."], ["Wertschöpfung", "Wert, den ein Wirtschaftsprozess zusätzlich schafft."]],
  vis: "line_sectors", cases: ["bengaluru", "frankfurt"],
  quiz: [
    ["Welcher Sektor wächst im Drei-Sektoren-Modell in hoch entwickelten Ländern am stärksten?", ["Tertiärer Sektor", "Primärer Sektor", "Sekundärer Sektor"], 0, "Dienstleistungen dominieren die Beschäftigung.", "Primär- und Sekundärsektor verlieren Anteile."],
    ["Warum konzentrieren sich Finanzdienstleistungen in wenigen Global Cities?", ["Fühlungsvorteile, Fachkräfte und internationale Vernetzung", "Günstige Mieten", "Große Rohstoffvorkommen"], 0, "Persönliche Kontakte und Netzwerke sind entscheidend.", "Global Cities sind teuer; Rohstoffe spielen keine Rolle."],
    ["Welche Dienstleistung wird am ehesten ins Ausland verlagert?", ["Standardisierter IT-Support", "Friseurbesuch", "Pflege im Krankenhaus"], 0, "Digital lieferbar und standardisiert.", "Personennahe Dienste müssen vor Ort erbracht werden."]
  ],
  task: { op: "erklären", afb: "II", prompt: "Erkläre den Wandel der Beschäftigtenstruktur mithilfe des Drei-Sektoren-Modells.", erw: ["Modellaussage", "Ursachen: Produktivitätsfortschritt, Nachfrageverschiebung, Globalisierung", "Anwendung auf Diagramm", "Folgen für Arbeitsmarkt und Raum"] } },

{ id: "tour", if: 7, t: "Wirtschaftsfaktor Tourismus", short: "Tourismus",
  goal: "Ich kann die Bedeutung des Tourismus für unterschiedlich entwickelte Räume erklären und Chancen, Risiken sowie Formen nachhaltigen Tourismus beurteilen.",
  wissen: ["Tourismus schafft direkte und indirekte Arbeitsplätze, Deviseneinnahmen und Infrastruktur; über Multiplikatoreffekte profitieren Landwirtschaft, Bau und Handwerk. Für viele Inselstaaten und Länder des Globalen Südens ist er ein Hauptwirtschaftszweig.",
    "Risiken: Saisonalität, Abhängigkeit von Krisen (Pandemie, Terror, Wechselkurse), Sickerrate (Einnahmen fließen an ausländische Konzerne ab), Flächen- und Wasserverbrauch, Overtourism, kultureller Wandel. Das Lebenszyklusmodell nach Butler beschreibt Entwicklung, Stagnation und möglichen Niedergang einer Destination.",
    "Nachhaltiger Tourismus will ökologische, ökonomische und soziale Ziele verbinden: Ökotourismus (z. B. Costa Rica), Community-based Tourism, Besucherlenkung, Ökosteuern (z. B. Tourismusabgabe auf den Balearen)."],
  terms: [["Multiplikatoreffekt", "Zusätzliche Einkommen in anderen Branchen durch Tourismusausgaben."], ["Sickerrate", "Anteil der Tourismuseinnahmen, der ins Ausland abfließt."], ["Saisonalität", "Starke Schwankung der Nachfrage im Jahresverlauf."], ["Overtourism", "Überlastung eines Ortes durch zu viele Touristen."], ["Ökotourismus", "Naturverträglicher Tourismus mit Nutzen für Schutz und Bevölkerung."], ["Lebenszyklusmodell", "Modell der Entwicklungsphasen einer Tourismusdestination (Butler)."], ["Besucherlenkung", "Steuerung von Besucherströmen, um Belastungen zu verringern."], ["All-inclusive", "Pauschalangebot mit Verpflegung, das lokale Ausgaben verringert."]],
  vis: "bar_season", cases: ["mallorca", "costarica"],
  quiz: [
    ["Was beschreibt die Sickerrate?", ["Anteil der Einnahmen, der ins Ausland abfließt", "Menge des Abwassers von Hotels", "Rückgang der Besucherzahlen"], 0, "Z. B. durch ausländische Hotelketten oder importierte Lebensmittel.", "Abwasser und Besucherrückgang sind andere Größen."],
    ["Warum können All-inclusive-Angebote lokale Effekte verringern?", ["Touristen geben außerhalb der Anlage weniger aus", "Sie erhöhen die Zahl lokaler Restaurants", "Sie verlängern die Saison automatisch"], 0, "Ausgaben bleiben in der Anlage.", "Sie schwächen eher lokale Gastronomie; Saisonlänge hängt nicht davon ab."],
    ["Was ist Ziel von Besucherlenkung?", ["Belastungen durch räumliche/zeitliche Steuerung verringern", "Mehr Touristen in dieselbe Zone bringen", "Den Tourismus verbieten"], 0, "Ströme verteilen, Schutzgebiete entlasten.", "Die anderen Optionen widersprechen dem Ziel."]
  ],
  task: { op: "(kritisch) Stellung nehmen", afb: "III", prompt: "Nimm Stellung zur Aussage: «Tourismus ist für Länder des Globalen Südens der beste Weg aus der Armut.»", erw: ["Aussage klären", "Pro: Devisen, Jobs, Multiplikator", "Contra: Sickerrate, Abhängigkeit, Saisonalität, Umwelt", "Eigene begründete Position (z. B. nur mit lokaler Beteiligung)"] } }
];
