/* ===== OFFIZIELLE NRW-GRUNDLAGEN (Abitur 2027, Englisch) ===== */
window.OFFICIAL = {
  subject: "Englisch",
  examDate: "2027-04-30T09:00:00+02:00",
  examDateLabel: "Freitag, 30. April 2027, 9:00 Uhr",
  kurse: {
    GK: {
      name: "Grundkurs",
      short: "GK",
      dauer: 285,
      teile: [
        { key: "HV", name: "Hörverstehen (isoliert)", min: 30, pts: 40, note: "i. d. R. 3 Hörtexte, zusammen ca. 10 Min., je zweimal gehört, keine Aufgabenwahl" },
        { key: "SM", name: "Sprachmittlung (isoliert)", min: 60, pts: 50, note: "max. 60 Min., deutscher Sach-/Gebrauchstext 450–650 Wörter, keine Aufgabenwahl" },
        { key: "SL", name: "Schreiben / Leseverstehen (integriert)", min: 195, pts: 110, note: "Text max. 800 Wörter, Wahl Aufgabe I (literarisch) oder II (Sach-/Gebrauchstext)" }
      ],
      ger: "B2, rezeptiv mit Anteilen von C1",
      hv: true
    },
    LK: {
      name: "Leistungskurs",
      short: "LK",
      dauer: 315,
      teile: [
        { key: "HV", name: "Hörverstehen (isoliert)", min: 30, pts: 40, note: "i. d. R. 3 Hörtexte, zusammen ca. 10 Min., je zweimal gehört, keine Aufgabenwahl" },
        { key: "SM", name: "Sprachmittlung (isoliert)", min: 60, pts: 50, note: "max. 60 Min., deutscher Sach-/Gebrauchstext 450–650 Wörter, keine Aufgabenwahl" },
        { key: "SL", name: "Schreiben / Leseverstehen (integriert)", min: 225, pts: 110, note: "Text max. 1.000 Wörter, Wahl Aufgabe I (literarisch) oder II (Sach-/Gebrauchstext)" }
      ],
      ger: "B2, rezeptiv mit Anteilen von C1 – höhere Komplexität und Abstraktion als im GK",
      hv: true
    }
  },
  // Soziokulturelles Orientierungswissen laut Vorgaben 2027 (Wortlaut der Vorgaben, gekürzt nach Themenfeld)
  fokus: {
    GK: [
      { t: "Das Vereinigte Königreich: Politik, Kultur, Gesellschaft – zwischen Wandel und Tradition", topic: "uk" },
      { t: "Das Vereinigte Königreich: Nationale Selbstkonzepte im Spiegel kolonialen Erbes und europäischer Verortung", topic: "ukself" },
      { t: "Die USA: Politik, Kultur, Gesellschaft – zwischen Wandel und Tradition", topic: "us" },
      { t: "Die USA: Amerikanische Ideale und Realitäten – Freiheit, Gleichheit und das Streben nach Glück", topic: "dream" },
      { t: "Nigeria: Politik, Kultur, Gesellschaft – zwischen Wandel und Tradition", topic: "nigeria" },
      { t: "Individuum & Gesellschaft: Fragen der Identität – Ambitionen und Hindernisse, Konformität vs. Individualismus", topic: "identity" },
      { t: "Individuum & Gesellschaft: Chancen und Herausforderungen – ethnische, kulturelle, soziale, sexuelle und geschlechtliche Vielfalt", topic: "diversity" },
      { t: "Medien: Journalismus zwischen Information und Unterhaltung; soziale Medien und digitale Plattformen – Teilhabe und Manipulation", topic: "media" },
      { t: "Literatur: Möglichkeiten und Herausforderungen klassischer und multimodaler Literaturformate", topic: "lit" },
      { t: "Welt im Wandel: Globalisierung – soziale, ökologische, wirtschaftliche Nachhaltigkeit; Migration; der globale Arbeitsmarkt", topic: "global" },
      { t: "Welt im Wandel: wissenschaftlicher und technischer Fortschritt als Chance und Herausforderung", topic: "tech" },
      { t: "Welt im Wandel: Zukunftsvisionen – utopische und dystopische Narrative", topic: "dystopia" }
    ],
    LK: [
      { t: "Das Vereinigte Königreich: Politik, Kultur, Gesellschaft – zwischen Wandel und Tradition", topic: "uk" },
      { t: "Das Vereinigte Königreich: Nationale Selbstkonzepte im Spiegel kolonialen Erbes und europäischer Verortung", topic: "ukself" },
      { t: "Die USA: Politik, Kultur, Gesellschaft – zwischen Wandel und Tradition", topic: "us" },
      { t: "Die USA: Amerikanische Ideale und Realitäten – Freiheit, Gleichheit und das Streben nach Glück", topic: "dream" },
      { t: "Nigeria: Politik, Kultur, Gesellschaft – zwischen Wandel und Tradition", topic: "nigeria" },
      { t: "Nigeria (nur LK): Das Erbe der britischen Herrschaft zwischen Aneignung und Abgrenzung", topic: "ngcol" },
      { t: "Individuum & Gesellschaft: Fragen der Identität – Ambitionen und Hindernisse, Konformität vs. Individualismus", topic: "identity" },
      { t: "Individuum & Gesellschaft: Chancen und Herausforderungen – ethnische, kulturelle, soziale, sexuelle und geschlechtliche Vielfalt", topic: "diversity" },
      { t: "Medien: Journalismus zwischen Information und Unterhaltung; soziale Medien und digitale Plattformen – Teilhabe und Manipulation", topic: "media" },
      { t: "Literatur: Möglichkeiten und Herausforderungen klassischer und multimodaler Literaturformate", topic: "lit" },
      { t: "Welt im Wandel: Globalisierung – soziale, ökologische, wirtschaftliche Nachhaltigkeit; Migration; der globale Arbeitsmarkt", topic: "global" },
      { t: "Welt im Wandel: wissenschaftlicher und technischer Fortschritt als Chance und Herausforderung", topic: "tech" },
      { t: "Welt im Wandel: Zukunftsvisionen – utopische und dystopische Narrative", topic: "dystopia" }
    ]
  },
  themenfelder: {
    GK: ["Das Vereinigte Königreich", "Die Vereinigten Staaten von Amerika", "Nigeria (weitere englischsprachige Bezugskultur)", "Das Individuum und die Gesellschaft im Wandel", "Medien und Literatur im Wandel", "Welt im Wandel"],
    LK: ["Das Vereinigte Königreich", "Die Vereinigten Staaten von Amerika", "Nigeria (weitere englischsprachige Bezugskultur)", "Das Individuum und die Gesellschaft im Wandel", "Medien und Literatur im Wandel", "Welt im Wandel"]
  },
  zieltexte: {
    GK: ["Zusammenfassung, Analyse, Stellungnahme", "Brief, E-Mail", "Leserbrief", "Blogeintrag", "Redebeitrag (z. B. Rede)", "Zeitungs- und Internetartikel", "Gestaltung, Fortführung oder Ergänzung narrativer Texte"],
    LK: ["Zusammenfassung, Analyse, Stellungnahme", "Brief, E-Mail", "Leserbrief", "Blogeintrag", "Redebeitrag (z. B. Rede)", "Zeitungs- und Internetartikel", "Gestaltung, Fortführung oder Ergänzung narrativer Texte", "zusätzlich im LK: Gestaltung, Fortführung oder Ergänzung dramatischer Texte"]
  },
  hilfsmittel: ["Ein- und zweisprachiges Wörterbuch", "Herkunftssprachliches Wörterbuch (wenn Herkunftssprache nicht Deutsch)", "Wörterbuch zur deutschen Rechtschreibung"],
  bewertungSL: {
    inhalt: 44, sprache: 66,
    kriterien: [
      ["Kommunikative Textgestaltung", [["Ausrichtung auf Intention und Adressat", 6], ["Textsortenmerkmale des Zieltextformats", 4], ["Sachgerecht strukturierter Text", 5], ["Hinreichend ausführlich, ohne Wiederholungen", 4], ["Funktionale Verweise und Zitate", 3]]],
      ["Ausdrucksvermögen / Verfügen über sprachliche Mittel", [["Löst sich vom Wortlaut, formuliert eigenständig", 5], ["Allgemeiner und thematischer Wortschatz", 6], ["Wortschatz zur Textproduktion und Textbesprechung", 4], ["Variabler, angemessener Satzbau", 7]]],
      ["Sprachrichtigkeit", [["Wortschatz", 9], ["Grammatik", 9], ["Orthografie (Rechtschreibung, Zeichensetzung)", 4]]]
    ]
  },
  bewertungSM: { inhalt: 20, textgestaltung: 10, ausdruck: 10, richtigkeit: 10 },
  noten200: [[190,15],[180,14],[170,13],[160,12],[150,11],[140,10],[130,9],[120,8],[110,7],[100,6],[90,5],[80,4],[66,3],[54,2],[40,1],[0,0]],
  noten160: [[152,15],[144,14],[136,13],[128,12],[120,11],[112,10],[104,9],[96,8],[88,7],[80,6],[72,5],[64,4],[53,3],[43,2],[32,1],[0,0]],
  sources: [
    { name: "Vorgaben Abitur 2027 – Englisch (geänderte Fassung, 25.08.2025)", url: "https://www.standardsicherung.schulministerium.nrw.de/system/files/media/document/file/englisch_2027_gg_neu.pdf" },
    { name: "Operatorenübersicht Englisch, gültig ab Abitur 2025 (30.08.2023)", url: "https://www.standardsicherung.schulministerium.nrw.de/system/files/media/document/file/e_operatoren_ab_abitur2025.pdf" },
    { name: "Konstruktionshinweise Klausuren moderne Fremdsprachen GOSt (27.10.2025)", url: "https://www.standardsicherung.schulministerium.nrw.de/system/files/media/document/file/konstruktionshinweise_klausuren_modernefs_gost_okt2025_0.pdf" },
    { name: "Termine Zentralabitur 2027 (Anlage A: Haupttermine)", url: "https://www.standardsicherung.schulministerium.nrw.de/system/files/media/document/file/anlage_a_termine_2027_ht.pdf" },
    { name: "Fachseite Englisch GOSt – Standardsicherung NRW", url: "https://www.standardsicherung.schulministerium.nrw.de/zentralabitur-gost/faecher/englisch-gost" },
    { name: "Konstruktionsvorgaben Abiturprüfungsaufgaben Englisch ab 2025 (30.08.2023)", url: "https://www.standardsicherung.schulministerium.nrw.de/system/files/media/document/file/konstruktionsvorgaben_englisch_ab_2025.pdf" },
    { name: "Kernlehrplan Englisch Sek. II (2023, Lehrplannavigator)", url: "https://lehrplannavigator.nrw.de/sekundarstufe-ii/kernlehrplaene-fuer-die-gymnasiale-oberstufe-ab-20222023/englisch-gymnasiale" }
  ]
};

/* ===== THEMEN (Schlüssel = Vokabelkategorien); en = englischer Titel ===== */
window.TOPICS = {
  uk: { en: "The UK: change and tradition", de: "UK: Politik, Kultur, Gesellschaft", official: true },
  ukself: { en: "Britain, Empire and Europe", de: "UK: koloniales Erbe & Europa (Brexit)", official: true },
  us: { en: "The USA: change and tradition", de: "USA: Politik, Kultur, Gesellschaft", official: true },
  dream: { en: "American ideals and realities", de: "USA: Freiheit, Gleichheit, Pursuit of Happiness", official: true },
  nigeria: { en: "Nigeria today", de: "Nigeria: Politik, Kultur, Gesellschaft", official: true },
  ngcol: { en: "Nigeria and the colonial legacy", de: "Nigeria: Erbe der britischen Herrschaft (LK)", official: true },
  identity: { en: "Identity and ambition", de: "Identität: Ambitionen, Konformität, Individualismus", official: true },
  diversity: { en: "Diversity in society", de: "Vielfalt: ethnisch, kulturell, sozial, sexuell, geschlechtlich", official: true },
  media: { en: "Journalism and social media", de: "Journalismus & soziale Medien", official: true },
  lit: { en: "Literature old and new", de: "Klassische & multimodale Literaturformate", official: true },
  global: { en: "Globalisation, migration, work", de: "Globalisierung, Migration, Arbeitsmarkt", official: true },
  tech: { en: "Science and technology", de: "Wissenschaftlicher & technischer Fortschritt", official: true },
  dystopia: { en: "Utopia and dystopia", de: "Utopische & dystopische Narrative", official: true },
  texto: { en: "Text analysis", de: "Wortschatz Textanalyse", official: false }
};

/* ===== VOKABELN: [en, de, topic, level 1-4, Beispiel] ===== */
window.VOCAB = [
  ["the monarchy", "die Monarchie", "uk", 1, "Support for the monarchy is much lower among young Britons than among older ones."],
  ["constitutional monarchy", "konstitutionelle Monarchie", "uk", 2, "In a constitutional monarchy, the King reigns but does not rule."],
  ["the House of Commons", "das Unterhaus", "uk", 1, "Laws are debated in the House of Commons before they go to the Lords."],
  ["the House of Lords", "das Oberhaus", "uk", 2, "Critics say an unelected House of Lords is out of date."],
  ["first-past-the-post", "Mehrheitswahlrecht", "uk", 3, "Under first-past-the-post, smaller parties rarely win many seats."],
  ["devolution", "Übertragung von Befugnissen an die Regionen", "uk", 3, "Devolution gave Scotland its own parliament in 1999."],
  ["the class system", "das Klassensystem", "uk", 2, "Accent is still seen as a marker of the class system."],
  ["the NHS (National Health Service)", "der staatliche Gesundheitsdienst", "uk", 1, "Many Britons see the NHS as a national treasure."],
  ["heritage", "das (kulturelle) Erbe", "uk", 2, "Stately homes are part of Britain's heritage industry."],
  ["to cling to tradition", "an der Tradition festhalten", "uk", 3, "Some institutions cling to tradition long after society has changed."],
  ["the cost-of-living crisis", "die Lebenshaltungskostenkrise", "uk", 2, "The cost-of-living crisis pushed many families into debt."],
  ["a public school (UK)", "eine teure Privatschule (UK)", "uk", 3, "A large share of cabinet ministers went to public schools."],

  ["the (British) Empire", "das (Britische) Weltreich", "ukself", 1, "At its height, the Empire covered about a quarter of the world's land."],
  ["the Commonwealth", "das Commonwealth", "ukself", 1, "The Commonwealth connects the UK with many former colonies."],
  ["colonial legacy", "koloniales Erbe", "ukself", 2, "Museums are rethinking how they present Britain's colonial legacy."],
  ["the Windrush generation", "Einwanderer aus der Karibik ab 1948", "ukself", 3, "The Windrush scandal showed how the state failed long-term residents."],
  ["Brexit", "der Austritt des UK aus der EU", "ukself", 1, "Brexit remains a divisive topic in British politics."],
  ["to leave / remain", "austreten / bleiben (EU-Referendum 2016)", "ukself", 2, "In 2016, a narrow majority voted to leave the EU."],
  ["sovereignty", "die Souveränität", "ukself", 3, "'Taking back control' was a slogan about sovereignty."],
  ["nostalgia", "die Nostalgie", "ukself", 2, "Some critics call it nostalgia for a Britain that never existed."],
  ["post-imperial", "postimperial", "ukself", 4, "The novel explores a post-imperial sense of loss."],
  ["restitution", "die Rückgabe (von Kulturgütern)", "ukself", 3, "Nigeria has demanded the restitution of the Benin Bronzes."],
  ["to come to terms with the past", "die Vergangenheit aufarbeiten", "ukself", 3, "A nation must come to terms with the past to move on."],

  ["the Constitution", "die Verfassung (USA)", "us", 1, "The Constitution has been amended 27 times."],
  ["the Bill of Rights", "die ersten zehn Verfassungszusätze", "us", 2, "Free speech is protected by the Bill of Rights."],
  ["checks and balances", "gegenseitige Kontrolle der Staatsgewalten", "us", 2, "Checks and balances are meant to prevent abuse of power."],
  ["the Supreme Court", "der Oberste Gerichtshof", "us", 1, "The Supreme Court decides whether laws are constitutional."],
  ["polarization", "die Polarisierung", "us", 2, "Political polarization makes compromise in Congress difficult."],
  ["partisan", "parteiisch, parteipolitisch", "us", 3, "Many voters only follow partisan news channels."],
  ["gun control", "Waffenkontrolle", "us", 1, "The debate on gun control flares up after every mass shooting."],
  ["the Second Amendment", "2. Verfassungszusatz (Recht auf Waffenbesitz)", "us", 2, ""],
  ["swing state", "umkämpfter Bundesstaat", "us", 2, "Candidates spend most of their money in swing states."],
  ["the Electoral College", "das Wahlmännerkollegium", "us", 3, "A candidate can win the Electoral College but lose the popular vote."],
  ["grassroots movement", "Basisbewegung", "us", 3, "The protest began as a grassroots movement on campus."],

  ["the American Dream", "der amerikanische Traum", "dream", 1, "For many immigrants, the American Dream still means a fresh start."],
  ["the pursuit of happiness", "das Streben nach Glück", "dream", 2, "The Declaration of Independence names life, liberty and the pursuit of happiness."],
  ["the land of opportunity", "das Land der unbegrenzten Möglichkeiten", "dream", 1, ""],
  ["upward (social) mobility", "sozialer Aufstieg", "dream", 3, "Studies show that upward mobility has slowed since the 1980s."],
  ["rags-to-riches story", "Vom-Tellerwäscher-zum-Millionär-Geschichte", "dream", 2, "Hollywood loves a rags-to-riches story."],
  ["the civil rights movement", "die Bürgerrechtsbewegung", "dream", 1, "The civil rights movement fought segregation in the 1950s and 60s."],
  ["segregation", "die Rassentrennung", "dream", 2, ""],
  ["systemic racism", "struktureller Rassismus", "dream", 3, "Activists argue that systemic racism shapes housing and policing."],
  ["the wealth gap", "die Vermögensschere", "dream", 2, "The wealth gap between white and Black households remains large."],
  ["self-reliance", "Eigenständigkeit, Selbstvertrauen", "dream", 3, "Self-reliance is a core value in American culture."],
  ["manifest destiny", "Ideologie der Westexpansion", "dream", 4, ""],
  ["to fall short of an ideal", "einem Ideal nicht gerecht werden", "dream", 3, "The country often falls short of its own ideals."],

  ["federal republic", "Bundesrepublik", "nigeria", 2, "Nigeria is a federal republic with 36 states."],
  ["Africa's most populous country", "das bevölkerungsreichste Land Afrikas", "nigeria", 1, ""],
  ["ethnic group", "ethnische Gruppe", "nigeria", 1, "The Hausa-Fulani, Yoruba and Igbo are the largest ethnic groups."],
  ["Nollywood", "die nigerianische Filmindustrie", "nigeria", 1, "Nollywood produces more films a year than almost any other industry."],
  ["Afrobeats", "Afrobeats (Musikstil)", "nigeria", 1, "Afrobeats artists fill stadiums in London and New York."],
  ["the oil economy", "die Ölwirtschaft", "nigeria", 2, "The oil economy has made a few people very rich."],
  ["corruption", "die Korruption", "nigeria", 1, ""],
  ["the tech hub", "das Technologiezentrum", "nigeria", 2, "Lagos has become a tech hub for start-ups."],
  ["youth unemployment", "die Jugendarbeitslosigkeit", "nigeria", 2, "Youth unemployment drives many graduates abroad."],
  ["japa (Nigerian slang)", "auswandern, das Land verlassen", "nigeria", 3, "'Japa' became the word for a whole generation's exodus."],
  ["#EndSARS", "Protestbewegung gegen Polizeigewalt (2020)", "nigeria", 3, "The #EndSARS protests were organised largely online."],
  ["Pidgin (English)", "nigerianisches Pidgin-Englisch", "nigeria", 2, "Pidgin is spoken across ethnic lines."],

  ["colonial rule", "die Kolonialherrschaft", "ngcol", 1, "Colonial rule in Nigeria ended in 1960."],
  ["indirect rule", "indirekte Herrschaft (über lokale Eliten)", "ngcol", 3, "Britain governed the north through indirect rule."],
  ["the amalgamation (of 1914)", "die Zusammenlegung der Protektorate 1914", "ngcol", 4, "The amalgamation of 1914 created one colony out of very different regions."],
  ["independence", "die Unabhängigkeit", "ngcol", 1, ""],
  ["the Biafran War", "der Biafra-Krieg (1967–1970)", "ngcol", 3, "The Biafran War still shapes memories in the south-east."],
  ["to appropriate", "sich aneignen", "ngcol", 3, "Writers appropriated English and made it their own."],
  ["to distance oneself from", "sich abgrenzen von", "ngcol", 3, "Some politicians distance themselves from British institutions."],
  ["lingua franca", "Verkehrssprache", "ngcol", 2, "English serves as a lingua franca in Nigeria."],
  ["postcolonial", "postkolonial", "ngcol", 2, "Achebe is a key postcolonial writer."],
  ["decolonise", "dekolonisieren", "ngcol", 3, "Students want to decolonise the curriculum."],

  ["peer pressure", "Gruppendruck", "identity", 1, "Peer pressure can make teenagers hide who they are."],
  ["to fit in", "dazugehören, sich anpassen", "identity", 1, "She changed her accent to fit in at university."],
  ["conformity", "die Konformität, Anpassung", "identity", 2, ""],
  ["to stand out", "herausstechen", "identity", 1, ""],
  ["aspiration", "das Streben, Ziel", "identity", 3, "Her parents' aspirations weighed heavily on her."],
  ["an obstacle", "ein Hindernis", "identity", 2, "Money is often the biggest obstacle to studying abroad."],
  ["self-image", "das Selbstbild", "identity", 2, ""],
  ["coming of age", "das Erwachsenwerden", "identity", 2, "The novel is a classic coming-of-age story."],
  ["to break free from expectations", "sich von Erwartungen befreien", "identity", 3, ""],
  ["belonging", "die Zugehörigkeit", "identity", 3, "The poem is about belonging to two places at once."],

  ["diversity", "die Vielfalt", "diversity", 1, ""],
  ["inclusion", "die Inklusion, Einbeziehung", "diversity", 2, "Inclusion means more than just inviting people in."],
  ["discrimination", "die Diskriminierung", "diversity", 1, ""],
  ["prejudice", "das Vorurteil", "diversity", 2, "Prejudice often grows out of ignorance."],
  ["equal opportunities", "Chancengleichheit", "diversity", 2, ""],
  ["LGBTQ+ rights", "Rechte queerer Menschen", "diversity", 2, "LGBTQ+ rights have expanded in many countries since 2000."],
  ["gender identity", "Geschlechtsidentität", "diversity", 3, ""],
  ["minority", "die Minderheit", "diversity", 1, ""],
  ["tolerance", "die Toleranz", "diversity", 1, ""],
  ["to marginalise", "an den Rand drängen", "diversity", 3, "Rural communities often feel marginalised."],
  ["multicultural", "multikulturell", "diversity", 1, "London is one of the most multicultural cities in the world."],

  ["breaking news", "Eilmeldung", "media", 1, ""],
  ["the quality press / tabloid", "Qualitätspresse / Boulevardzeitung", "media", 2, "The tabloid ran the story with a sensational headline."],
  ["infotainment", "Infotainment", "media", 2, ""],
  ["clickbait", "Klickköder", "media", 2, "Clickbait headlines promise more than the article delivers."],
  ["fake news / disinformation", "Falschmeldung / Desinformation", "media", 2, "Disinformation spreads faster than corrections."],
  ["filter bubble / echo chamber", "Filterblase / Echokammer", "media", 2, "Algorithms can trap users in an echo chamber."],
  ["algorithm", "der Algorithmus", "media", 2, ""],
  ["to go viral", "sich rasend verbreiten", "media", 1, ""],
  ["fact-checking", "Faktenprüfung", "media", 2, ""],
  ["citizen journalism", "Bürgerjournalismus", "media", 3, "During the protests, citizen journalism filled the gaps."],
  ["to manipulate", "manipulieren", "media", 2, ""],
  ["digital participation", "digitale Teilhabe", "media", 3, "Social media offers new forms of digital participation."],

  ["the novel / short story", "der Roman / die Kurzgeschichte", "lit", 1, ""],
  ["the graphic novel", "die Graphic Novel", "lit", 1, "The graphic novel tells the story in images and text."],
  ["multimodal", "multimodal (Text, Bild, Ton kombiniert)", "lit", 3, "Multimodal texts combine words, images and sound."],
  ["the adaptation", "die Verfilmung, Bearbeitung", "lit", 2, "The film adaptation changes the ending."],
  ["the canon", "der (literarische) Kanon", "lit", 3, "Should Shakespeare remain at the centre of the canon?"],
  ["spoken word poetry", "Spoken-Word-Lyrik", "lit", 2, ""],
  ["the audio drama / podcast fiction", "Hörspiel / fiktionaler Podcast", "lit", 2, ""],
  ["BookTok", "Buchempfehlungen auf TikTok", "lit", 2, "BookTok has turned old novels into bestsellers."],
  ["the stage direction", "die Regieanweisung", "lit", 2, "The stage directions describe a cramped kitchen."],
  ["soliloquy", "der Monolog (allein auf der Bühne)", "lit", 3, "In his soliloquy, the character reveals his doubts."],

  ["globalisation", "die Globalisierung", "global", 1, ""],
  ["sustainability", "die Nachhaltigkeit", "global", 2, ""],
  ["supply chain", "die Lieferkette", "global", 2, "The pandemic exposed fragile supply chains."],
  ["fast fashion", "Fast Fashion", "global", 1, "Fast fashion relies on cheap labour abroad."],
  ["carbon footprint", "CO₂-Fußabdruck", "global", 2, ""],
  ["migrant worker", "Arbeitsmigrant/in", "global", 2, ""],
  ["refugee / asylum seeker", "Flüchtling / Asylbewerber/in", "global", 1, ""],
  ["brain drain", "Abwanderung von Fachkräften", "global", 2, "Nigeria suffers from a brain drain of doctors and nurses."],
  ["remittances", "Rücküberweisungen von Migranten", "global", 3, "Remittances are a major source of income for many families."],
  ["the gig economy", "die Plattformökonomie (Gelegenheitsjobs)", "global", 2, "Delivery riders are part of the gig economy."],
  ["outsourcing", "die Auslagerung", "global", 2, ""],
  ["fair trade", "fairer Handel", "global", 1, ""],

  ["artificial intelligence (AI)", "künstliche Intelligenz (KI)", "tech", 1, ""],
  ["automation", "die Automatisierung", "tech", 2, "Automation threatens routine office jobs."],
  ["genetic engineering", "die Gentechnik", "tech", 2, ""],
  ["surveillance", "die Überwachung", "tech", 2, "Facial recognition makes mass surveillance cheaper."],
  ["data privacy", "der Datenschutz", "tech", 2, ""],
  ["ethical concerns", "ethische Bedenken", "tech", 2, "Designer babies raise serious ethical concerns."],
  ["a double-edged sword", "ein zweischneidiges Schwert", "tech", 3, "Technology is a double-edged sword."],
  ["to regulate", "regulieren", "tech", 2, ""],
  ["breakthrough", "der Durchbruch", "tech", 2, ""],

  ["dystopia / utopia", "Dystopie / Utopie", "dystopia", 1, ""],
  ["totalitarian", "totalitär", "dystopia", 2, "The novel depicts a totalitarian state."],
  ["the protagonist", "die Hauptfigur", "dystopia", 1, ""],
  ["to rebel against", "sich auflehnen gegen", "dystopia", 2, ""],
  ["a cautionary tale", "eine warnende Erzählung", "dystopia", 3, "Dystopian fiction is often read as a cautionary tale."],
  ["propaganda", "die Propaganda", "dystopia", 2, ""],
  ["to be under constant surveillance", "ständig überwacht werden", "dystopia", 2, ""],
  ["to extrapolate from the present", "aus der Gegenwart hochrechnen", "dystopia", 4, "Good dystopias extrapolate from the present."],

  ["the narrator (first-person / third-person)", "der Ich- / Er-Erzähler", "texto", 2, ""],
  ["omniscient narrator", "allwissender Erzähler", "texto", 3, ""],
  ["point of view", "die Erzählperspektive", "texto", 2, ""],
  ["rhetorical question", "rhetorische Frage", "texto", 2, ""],
  ["enumeration", "die Aufzählung", "texto", 2, ""],
  ["alliteration", "die Alliteration", "texto", 2, ""],
  ["anaphora", "die Anapher", "texto", 3, ""],
  ["metaphor / simile", "Metapher / Vergleich (mit like/as)", "texto", 2, ""],
  ["irony", "die Ironie", "texto", 2, ""],
  ["hyperbole", "die Übertreibung", "texto", 3, ""],
  ["register (formal / informal)", "Sprachebene (formell / informell)", "texto", 3, ""],
  ["to emphasise", "betonen, hervorheben", "texto", 2, "The author emphasises the urgency of the problem."],
  ["to appeal to the reader", "an den Leser appellieren", "texto", 2, ""],
  ["tone / atmosphere", "Ton / Atmosphäre", "texto", 2, ""]
];
