/* ===== ÜBUNGSTEXTE (eigens erstellt, fiktive Personen) ===== */
window.LISTEN = {
  hv1: { title: "Margate: a seaside town reinvents itself", voice: "en-GB", accent: "British English", topic: "uk", lvl: 3,
    pre: [["seaside resort", "Badeort"], ["run-down", "heruntergekommen"], ["to be priced out", "durch hohe Preise verdrängt werden"], ["the locals", "die Einheimischen"], ["a DFLer (slang)", "Zugezogene/r aus London ('down from London')"]],
    text: "This is Coast to Coast on Radio South. I'm standing on the beach in Margate, a seaside town in Kent, about ninety minutes from London by train. For most of the twentieth century, working-class families from London spent their summer holidays here. Then cheap flights to Spain arrived, the tourists left, and by the early two-thousands many shops on the high street were boarded up. Today the town looks very different. There is a large art gallery on the seafront, vintage shops, cafés selling oat-milk lattes and a restored amusement park. Many of the new residents are artists and young professionals who moved here during the pandemic, when they could suddenly work from home. Julie Watts has run a fish-and-chip shop on the promenade for thirty-one years. 'Business has never been better,' she tells me. 'But my own daughter can't afford to rent a flat in the town she grew up in.' Local housing groups say rents have risen far faster than wages, and that some long-standing residents feel like strangers in their own town. Others see the change as a second chance. Dev Patel, a young designer who grew up here and moved back last year, puts it like this: 'Margate had been forgotten. Now people are talking about it again. The challenge is to make sure that the people who stayed through the hard times are not left behind.'",
    q: [
      { type: "mc", op: "tick", q: "Why did Margate decline as a holiday destination?", o: ["The beach became polluted", "Holidays abroad became cheap", "The train line to London closed"], a: 1 },
      { type: "mc", op: "tick", q: "Many new residents moved to Margate because…", o: ["they could work remotely", "they found jobs at the gallery", "the council offered them flats"], a: 0 },
      { type: "short", op: "state", q: "How long has Julie Watts run her shop? (number)", keys: ["31", "thirty-one", "thirty one"], a: "31 years" },
      { type: "mc", op: "tick", q: "Julie's main concern is that…", o: ["she has fewer customers", "her daughter cannot find affordable housing", "tourists are rude"], a: 1 },
      { type: "short", op: "complete", q: "According to housing groups, rents have risen faster than ______.", keys: ["wage", "salar", "income", "pay"], a: "wages" },
      { type: "mc", op: "tick", q: "(inferierend) Dev Patel's attitude to the changes is…", o: ["entirely negative", "positive but aware of the risks", "indifferent"], a: 1 }
    ] },
  hv2: { title: "First in the family: going to college in Ohio", voice: "en-US", accent: "American English", topic: "dream", lvl: 3,
    pre: [["first-generation student", "erste Person in der Familie, die studiert"], ["tuition", "Studiengebühren"], ["student loan", "Studienkredit"], ["to drop out", "abbrechen"], ["a shift", "eine Schicht (Arbeit)"]],
    text: "Welcome back to Campus Voices. My guest today is Maria Delgado. Maria is twenty and studies nursing at a state university in Ohio. She's also the first person in her family to go to college. Maria, what did your parents say when you got in? They cried, honestly. My dad came here from Mexico when he was nineteen. He's worked in a meat-packing plant for twenty-two years. For him, me going to college is the whole reason he came. That's the American Dream for my family. So is it a dream come true? Partly. The hardest thing is money. Even with a scholarship, I still had to take out a student loan, and I work three evening shifts a week at a supermarket. Some of my classmates have parents who pay for everything. They don't understand why I can't just go out on a Tuesday night. What about the academic side? At first I felt lost. Nobody in my family could explain what office hours are or how to write a research paper. I almost dropped out after my first semester. What changed? The university has a mentoring program for first-generation students. My mentor is a senior who went through the same thing. She showed me that asking for help isn't a weakness. And your plans? I want to work in a hospital in a small town, where they really need nurses. And I want to pay off my loan before I'm thirty. That's my version of the dream: not getting rich, just being free to choose.",
    q: [
      { type: "mc", op: "tick", q: "What does Maria study?", o: ["Medicine", "Nursing", "Business"], a: 1 },
      { type: "short", op: "state", q: "How old was Maria's father when he came to the US?", keys: ["19", "nineteen"], a: "nineteen" },
      { type: "short", op: "list", q: "Name ONE way Maria pays for college.", keys: ["scholarship", "loan", "supermarket", "shift", "work"], a: "scholarship / student loan / job at a supermarket" },
      { type: "mc", op: "tick", q: "Why did Maria struggle academically at first?", o: ["Her classes were in Spanish", "Nobody at home knew how university works", "She had to repeat a year"], a: 1 },
      { type: "mc", op: "tick", q: "What helped her to stay at university?", o: ["A mentoring program", "A lower workload", "Her father's advice"], a: 0 },
      { type: "mc", op: "tick", q: "(inferierend) For Maria, the American Dream means…", o: ["becoming wealthy", "having the freedom to make her own choices", "moving to a big city"], a: 1 }
    ] },
  hv3: { title: "Lagos: to stay or to 'japa'?", voice: "en-NG", accent: "Nigerian English", topic: "nigeria", lvl: 4,
    pre: [["to japa", "(Nigerian Pidgin) auswandern"], ["start-up", "junges Unternehmen"], ["power cut", "Stromausfall"], ["the diaspora", "die Diaspora (im Ausland lebende Gemeinschaft)"], ["to invest", "investieren"]],
    text: "Good evening, and welcome to Lagos Talks. Tonight we are in a co-working space in Yaba, a district many people call the heart of Nigeria's tech scene. Around me, young people are working on laptops, some of them with a generator humming outside, because power cuts are still part of daily life. Tolu is twenty-six. She co-founded a start-up that helps market traders accept digital payments. Three of her university friends have already left the country, two for the UK and one for Canada. 'Every week someone on my WhatsApp says they're leaving,' she says. 'I understand them. Prices are rising, salaries are not.' So why does she stay? 'Because the problems here are also opportunities. Millions of people still don't have a bank account. If we can solve that, we change lives.' Her business partner, Emeka, left for Manchester in 2021 and came back last year. 'Abroad, I was just another software developer,' he explains. 'Here, I can build something of my own.' Both of them say the diaspora plays an important role: friends abroad send money home, share contacts and sometimes invest in local businesses. 'Leaving is not always the end of the story,' Emeka says. 'Sometimes it is the beginning of a connection.'",
    q: [
      { type: "mc", op: "tick", q: "Why is there a generator outside the co-working space?", o: ["Electricity is unreliable", "It is used for heating", "The building is new"], a: 0 },
      { type: "mc", op: "tick", q: "What does Tolu's start-up do?", o: ["It trains software developers", "It helps traders use digital payments", "It helps people apply for visas"], a: 1 },
      { type: "short", op: "state", q: "How many of Tolu's university friends have left Nigeria?", keys: ["3", "three"], a: "three" },
      { type: "mc", op: "tick", q: "Why did Emeka return to Nigeria?", o: ["He lost his job in Manchester", "He wanted to build his own business", "His family asked him to"], a: 1 },
      { type: "short", op: "name", q: "Name ONE way the diaspora supports people in Nigeria.", keys: ["money", "contact", "invest"], a: "sending money / sharing contacts / investing" },
      { type: "mc", op: "tick", q: "(inferierend) Which statement best reflects the report's message?", o: ["Emigration only harms Nigeria", "Emigration and staying can both create opportunities", "All young Nigerians want to leave"], a: 1 }
    ] },
  hv4: { title: "News from influencers: a panel discussion", voice: "en-GB", accent: "British English", topic: "media", lvl: 3,
    pre: [["news influencer", "Person, die Nachrichten in sozialen Medien verbreitet"], ["accountability", "Rechenschaftspflicht"], ["to verify", "überprüfen"], ["trustworthy", "vertrauenswürdig"]],
    text: "Welcome to Media Matters. A recent survey suggested that many people under twenty-five now get most of their news from individual creators on social media rather than from newspapers or TV channels. With me are Hannah, a media teacher, and Kofi, who runs a news channel with half a million followers. Kofi, why do young people trust you? I think because I talk to them like a friend. I explain what a story means for their lives, in two minutes, without jargon. Hannah, is that a problem? Not in itself. Kofi's videos are clear and he links to his sources. The problem is that not every creator works like that. A newspaper has editors, corrections and legal accountability. An influencer can post a rumour at midnight and delete it in the morning. Kofi, do you check your facts? Always. I compare at least two reliable sources before I post anything. But I admit I'm under pressure to be first, because the algorithm rewards speed. Hannah, what should schools do? Teach young people to ask three questions: who is telling me this, how do they know, and who benefits if I believe it. That works for a TikTok video and for a front page.",
    q: [
      { type: "mc", op: "tick", q: "According to the survey, many young people get their news mainly from…", o: ["TV channels", "individual creators online", "newspapers"], a: 1 },
      { type: "mc", op: "tick", q: "Kofi thinks young people trust him because…", o: ["he is a trained journalist", "he speaks to them in a personal, simple way", "he posts very long videos"], a: 1 },
      { type: "short", op: "list", q: "Name ONE thing newspapers have that influencers often lack.", keys: ["editor", "correction", "accountab", "legal"], a: "editors / corrections / legal accountability" },
      { type: "short", op: "state", q: "How many sources does Kofi compare before posting?", keys: ["2", "two", "at least two"], a: "at least two" },
      { type: "mc", op: "tick", q: "What puts Kofi under pressure?", o: ["His sponsors", "The algorithm rewards speed", "His teachers"], a: 1 },
      { type: "short", op: "complete", q: "Hannah's first question: Who is ______ me this?", keys: ["telling"], a: "telling" }
    ] }
};

window.READ = {
  r1: { title: "Why I Logged Off for a Year", kind: "Blog post", lvl: 2, ger: "B1/B2", topic: "media",
    paras: [
      "Last September I did something my friends called 'social suicide': I deleted Instagram, TikTok and Snapchat from my phone. No big announcement, no farewell post. I just wanted to find out who I was when nobody was watching.",
      "The first two weeks were strange. I kept reaching for my phone every few minutes, the way you touch your pocket when you think you've lost your keys. I missed party invitations and in-jokes. On the bus, I noticed for the first time how many people were staring at screens – and I wondered how often I had looked exactly like that.",
      "Then something shifted. I started reading again, real books, three in October alone. I got better sleep. I stopped comparing my ordinary Tuesday with someone else's holiday in Bali. Most surprisingly, the friends who mattered found other ways to reach me: they called, they texted, they knocked on my door.",
      "Not everything was better. I missed out on news from my cousins in Canada, and a school project was organised entirely in a group chat I wasn't in. Being offline is a privilege: not everyone can afford to disappear, especially if your job or your community lives online.",
      "So will I go back? Probably, but on my own terms. I've learned that the apps aren't the problem in themselves. The problem is letting an algorithm decide how I spend my attention. This time, I want to be the one in control."
    ],
    ex: [
      { type: "mc", q: "Why did the blogger delete the apps?", o: ["Her parents made her", "She wanted to discover who she was without an audience", "Her phone was broken"], a: 1, why: "Paragraph 1: 'find out who I was when nobody was watching'." },
      { type: "mc", q: "The comparison with losing keys (paragraph 2) shows…", o: ["that she often lost things", "how automatic her phone habit was", "that she was stressed about school"], a: 1, why: "Vergleich (simile) → unbewusste, automatische Gewohnheit." },
      { type: "match", q: "Match each paragraph with a heading.", pairs: [["Paragraph 1", "The decision"], ["Paragraph 2", "Withdrawal symptoms"], ["Paragraph 3", "Unexpected benefits"], ["Paragraph 4", "The downside"], ["Paragraph 5", "Lessons learned"]] },
      { type: "mc", q: "'on my own terms' means…", o: ["zu meinen eigenen Bedingungen", "mit eigenen Worten", "auf eigene Kosten"], a: 0, why: "on one's own terms = selbstbestimmt, zu den eigenen Bedingungen." },
      { type: "evidence", q: "Tippe den Satz an, der zeigt, dass die Autorin ihre Lage als privilegiert ansieht.", para: 3, sentenceKey: "Being offline is a privilege" }
    ] },
  r2: { title: "The Dream on Main Street", kind: "Feature article (Sachtext)", lvl: 3, ger: "B2", topic: "dream",
    paras: [
      "On a Saturday morning in Harlow Falls, Pennsylvania, the diner on Main Street is full. Farmers in baseball caps sit next to nurses coming off the night shift. The walls are covered in photos of the town's glory days: a steel mill employing three thousand people, a high-school football team that won the state title, a Fourth of July parade that stretched for a mile.",
      "The mill closed in 1998. Today, the biggest employer is a warehouse on the edge of town, where workers scan parcels for twelve-hour shifts. 'My grandfather bought a house, a car and a boat on one income,' says Kyle Brandt, 34, who works there. 'I have two jobs and I still rent.' Across the table, his friend nods. Nobody laughs.",
      "Ask people in Harlow Falls about the American Dream and you get two answers, often from the same person. The first is anger: the rules changed, the factories moved abroad, and politicians in Washington stopped listening. The second is stubborn hope. Kyle's sister runs a small bakery that sells sourdough online to customers in three states. A former mill worker retrained as a wind turbine technician. 'Nobody is coming to save us,' says the mayor, a retired teacher. 'So we save ourselves.'",
      "Economists have long argued about whether the Dream is dying or just changing shape. What is clear is that the promise of hard work leading to a better life than your parents' feels less certain than it did two generations ago. In places like Harlow Falls, the Dream has not disappeared. It has become smaller, more personal and more fragile: a paid-off car loan, a child who goes to college, a business that survives another winter.",
      "At noon, the diner empties. Outside, a banner from last summer's parade still hangs across Main Street. It reads: 'Harlow Falls – Still Standing.' Whether that is a statement of pride or a cry for help depends on who you ask."
    ],
    ex: [
      { type: "mc", q: "What is the function of the first paragraph?", o: ["It presents statistics on unemployment", "It creates a vivid picture of the town and its past", "It criticises the townspeople"], a: 1, why: "Szenischer Einstieg (Diner, Fotos) → anschaulich, emotional." },
      { type: "mc", q: "Kyle's statement about his grandfather illustrates…", o: ["declining social mobility", "rising house prices in cities", "his wish to buy a boat"], a: 0, why: "Kontrast: früher ein Einkommen genügte, heute zwei Jobs → Aufstieg schwieriger." },
      { type: "mc", q: "According to paragraph 3, the townspeople's attitude is…", o: ["purely optimistic", "a mixture of anger and hope", "completely resigned"], a: 1, why: "'two answers, often from the same person': anger and stubborn hope." },
      { type: "mc", q: "The last sentence of the article is…", o: ["ambiguous and leaves the judgement to the reader", "a clear call for political action", "a summary of statistics"], a: 0, why: "Offenes Ende: pride or cry for help – Rahmen (Diner → Banner)." },
      { type: "evidence", q: "Tippe den Satz an, in dem der Autor die Veränderung des Traums zusammenfasst.", para: 3, sentenceKey: "It has become smaller" }
    ] },
  r3: { title: "Whose History? – A Speech on Statues", kind: "Speech (Sachtext)", lvl: 4, ger: "B2/C1", topic: "ukself",
    paras: [
      "Friends, neighbours, members of the council – thank you for letting me speak. Two weeks ago, someone sprayed the word 'SHAME' on the statue of Sir Edward Holt in our market square. Since then, this town has talked about little else. Some of you want the statue removed. Some of you want it guarded day and night. I want to suggest a third way.",
      "Let us be honest about who Edward Holt was. He built the hospital that many of us were born in. He paid for the library where I learned to read. And he made his fortune from sugar plantations worked by enslaved people. All of these things are true at the same time. A statue, however, does not tell three truths. It tells one: this man deserves our admiration.",
      "Some say that removing statues is 'erasing history'. I disagree. History is not kept in bronze; it is kept in archives, in schools, in the stories we tell our children. We did not erase history when we took down the portraits of kings who burned their enemies alive. We simply stopped celebrating them.",
      "Others say: leave the past in the past. But the past is not past for everyone. When a Black child walks across our square every morning on the way to school, what does that statue say to her about who belongs here, and who is honoured here?",
      "So here is my proposal. Let us move the statue to the town museum, where it can be displayed with its full history – the hospital, the library and the plantations. And in the square, let us put up something new, chosen by the people who live here now. Not to forget, but to remember better. Thank you."
    ],
    ex: [
      { type: "mc", q: "What is the speaker's main aim?", o: ["To defend the statue as it is", "To propose a compromise between removal and keeping", "To demand that Holt's buildings are closed"], a: 1, why: "'I want to suggest a third way' (para 1) + Vorschlag Museum (para 5)." },
      { type: "mc", q: "In paragraph 2, the speaker uses an enumeration to…", o: ["show that Holt's legacy is complex", "praise Holt", "list the council's mistakes"], a: 0, why: "hospital, library, plantations → 'All of these things are true at the same time'." },
      { type: "mc", q: "The question in paragraph 4 is…", o: ["a rhetorical question that appeals to the audience's empathy", "a request for information", "an ironic joke"], a: 0, why: "Rhetorische Frage + konkretes Bild (Kind) → emotionaler Appell (pathos)." },
      { type: "mc", q: "The final sentence 'Not to forget, but to remember better' is an example of…", o: ["antithesis/parallelism", "alliteration", "hyperbole"], a: 0, why: "Gegenüberstellung in paralleler Struktur → einprägsamer Schluss." },
      { type: "evidence", q: "Tippe den Satz an, in dem die Rednerin ein Gegenargument aufgreift.", para: 2, sentenceKey: "Some say that removing statues" }
    ] }
};

window.LIT = {
  l1: { title: "The Quiet Hour", kind: "Short story (dystopian)", author: "Übungstext", lvl: 4, topic: "dystopia",
    paras: [
      "At seven o'clock every evening, the Quiet Hour began. The streetlights dimmed to a soft blue, the trams stopped mid-track, and every screen in the city displayed the same message: REST IS RESPONSIBILITY. For sixty minutes, citizens were expected to sit still, breathe slowly and let their Companions measure their calm.",
      "Nia had never missed a Quiet Hour. Her Companion – a thin silver band around her wrist – glowed green every night, and every month the Ministry sent her a small reward: extra water credits, once a ticket to the sea. Her score was 98. Her mother's had been 97 until the night she stopped wearing her band. After that, her mother had been 'transferred to a restful environment'. Nobody said where.",
      "Tonight, Nia sat by the window as usual. The blue light washed over the empty square. Then she saw him: a boy of perhaps ten, running across the square, laughing, his arms spread like wings. His wrist was bare.",
      "Her Companion vibrated. HEART RATE RISING. PLEASE RETURN TO CALM. She forced herself to breathe. In. Out. The boy stopped in the middle of the square, looked up, and for a moment Nia was sure he was looking directly at her window. He waved.",
      "She did not wave back. She watched the two grey vans arrive, silent as always, and she watched the boy disappear into one of them. Her Companion glowed green again. Score: 99. A new record.",
      "Later that night, when the lights came back and the trams moved again, Nia took off her silver band for the first time in eleven years. She held it in her palm for a long time. It was lighter than she had expected."
    ],
    focus: ["Setting: controlled society, rituals of 'rest' (para 1)", "Euphemisms: 'Companion', 'restful environment', REST IS RESPONSIBILITY", "Third-person narrator, limited to Nia's perspective", "The boy as a symbol of freedom (simile: arms like wings)", "Irony: record score at the moment of moral failure", "Open ending: the weightless band – beginning of rebellion?"] },
  l2: { title: "The Visit", kind: "Drama excerpt (Szene, LK: dramatische Texte)", author: "Übungstext", lvl: 4, topic: "identity",
    paras: [
      "A small kitchen in Peckham, South London. Evening. A pot is boiling on the stove. FUNMI (50s) is cutting peppers. Her daughter TEMI (19) enters with a suitcase, still wearing her coat.",
      "FUNMI (without looking up): You said six o'clock. TEMI: The train was late. Hello, Mummy. FUNMI: Hello. Sit. The stew is almost ready.",
      "TEMI (not sitting): I need to tell you something before Daddy comes home. FUNMI (putting the knife down, slowly): You are pregnant. TEMI: What? No! Mummy, no. FUNMI (relieved, picking up the knife again): Good. Then sit.",
      "TEMI: I've changed my course. I'm not doing Law any more. I'm doing Drama. (Pause. The pot boils over. Neither of them moves.)",
      "FUNMI: Drama. (She turns off the stove.) Your father worked two jobs for twenty years. Nights at the hospital, weekends driving a taxi. So that his daughter could stand on a stage and pretend? TEMI: So that his daughter could choose. That's what he always said. 'In this country you can be anything.' FUNMI: He meant a lawyer, Temi. Or a doctor. Anything that does not need an audience to pay the rent.",
      "TEMI (quietly): I'm good at it, Mummy. For the first time in my life, I'm really good at something. FUNMI (after a long pause, not unkindly): In Lagos, when I was your age, I sang in the church choir. Everyone said I should go to music school. (She begins to wipe the stove.) My father laughed for a whole week. TEMI: You never told me that. FUNMI: You never asked. (The sound of a key in the door. Both women freeze.)"
    ],
    focus: ["Stage directions reveal emotion (knife, boiling pot, freezing)", "Dramatic irony: mother's misunderstanding (pregnancy) – comic relief", "Generational conflict: security vs. self-fulfilment (American/British Dream of the migrant parents)", "Symbolism: the pot boiling over = tension; turning off the stove", "Turning point: Funmi's confession about the choir – parallel between generations", "Open ending: the father's arrival (cliffhanger)"] }
};

window.MEDIATION = {
  sm1: { title: "Handyverbot an deutschen Schulen", lvl: 2, words: 210, topic: "media", len: "kurz",
    situation: "Your Irish friend Aoife is writing an article for her school magazine about how different European countries deal with smartphones in schools. She asked you about the situation in Germany. You found this German article.",
    task: "Write an e-mail to Aoife in which you outline the rules and the arguments presented in the article.",
    source: [
      "Schulen ohne Smartphone: Mehr Ruhe auf dem Pausenhof?",
      "Immer mehr Schulen in Deutschland schränken die private Handynutzung ein. In mehreren Bundesländern gibt es inzwischen landesweite Vorgaben, in anderen entscheiden die Schulen selbst. Am Gymnasium in Musterstadt gilt seit einem Jahr: Handys bleiben während des gesamten Schultags ausgeschaltet im Spind.",
      "„Die Pausen sind lauter geworden – im positiven Sinn“, sagt Schulleiterin Birgit Kramer. Schülerinnen und Schüler spielten wieder Tischtennis oder unterhielten sich. Auch Fälle von Cybermobbing während der Schulzeit seien zurückgegangen.",
      "Nicht alle sind begeistert. Der 17-jährige Schülersprecher Jonas findet die Regel zu streng: „Wir sollen lernen, verantwortungsvoll mit digitalen Medien umzugehen. Das geht nicht, wenn man sie einfach wegsperrt.“ Einige Eltern kritisieren außerdem, dass sie ihre Kinder in Notfällen nicht erreichen können.",
      "Die Schule hat deshalb einen Kompromiss gefunden: In der Oberstufe dürfen Handys im Unterricht genutzt werden, wenn die Lehrkraft es für Recherchen erlaubt. Für Notfälle steht das Telefon im Sekretariat zur Verfügung."
    ],
    relevant: ["More and more German schools restrict private phone use; some states have rules, elsewhere schools decide", "Example school: phones switched off in lockers all day", "Positive effects: more activity/talk in breaks, less cyberbullying", "Criticism: students should learn responsible use (student representative)", "Parents: cannot reach children in emergencies", "Compromise: upper school may use phones for research with teacher permission; office phone for emergencies"],
    irrelevant: ["Name of the head teacher", "Exact age of the student representative", "Table tennis (optional detail)"],
    cultural: ["'Bundesländer' → Germany's 16 federal states, which are responsible for education", "'Oberstufe' → the last years of secondary school (like sixth form / senior cycle)", "'Schülersprecher' → elected student representative"],
    model: "Hi Aoife,\n\nThanks for your message – your article sounds really interesting! I found a German newspaper article that fits your topic perfectly.\n\nIn Germany, more and more schools are restricting the use of private smartphones. Because education is the responsibility of the 16 federal states, some states have introduced general rules, while elsewhere each school decides for itself. The article describes a grammar school where students have to keep their phones switched off in their lockers all day.\n\nAccording to the head teacher, the rule has had positive effects: students talk and play together again during breaks, and there has been less cyberbullying during school hours.\n\nHowever, not everyone agrees. The elected student representative argues that young people should learn to use digital media responsibly, which is impossible if phones are simply locked away. Some parents also complain that they can't reach their children in an emergency.\n\nThe school has found a compromise: students in the final years (a bit like your senior cycle) may use their phones in class if the teacher allows it for research, and in an emergency students can use the phone in the school office.\n\nI hope this helps! Let me know if you need anything else.\n\nBest wishes,\n[Name]",
    why: ["Anrede + Bezug auf Aoifes Artikel (Adressat, Anlass)", "Bundesländer/Oberstufe kulturell erklärt", "Namen und Alter weggelassen", "Gliederung: Regel → Pro → Contra → Kompromiss", "Informelles, aber klares Register"] },
  sm2: { title: "Duale Ausbildung statt Studium?", lvl: 3, words: 490, topic: "global", len: "Abiturniveau",
    situation: "Your American friend Jayden, who is in his last year of high school in Chicago, is unsure whether to go to college. He has heard that in Germany many young people do an apprenticeship instead, and he asks you to tell him more. You come across the following article in a German magazine.",
    task: "Write an e-mail to Jayden in which you explain how the German system of vocational training works according to the article and what experiences young people have had with it.",
    source: [
      "Lehre statt Hörsaal: Warum sich Abiturientinnen und Abiturienten wieder für eine Ausbildung entscheiden",
      "Als Lena Hoffmann vor drei Jahren ihr Abitur mit 1,6 bestand, war für ihre Eltern klar: Jetzt wird studiert. Lena entschied sich anders – für eine Ausbildung zur Mechatronikerin bei einem mittelständischen Maschinenbauunternehmen in Baden-Württemberg. „Meine Oma fragte bei jedem Familienfest, wann ich denn endlich an die Uni gehe“, erzählt die 22-Jährige und lacht. Inzwischen ist die Ausbildung abgeschlossen, Lena hat einen unbefristeten Arbeitsvertrag – und ihre Oma zeigt die Fotos vom Firmenstand auf der Messe allen Nachbarinnen.",
      "Lena ist kein Einzelfall. Die duale Ausbildung, um die Deutschland im Ausland oft beneidet wird, erlebt unter Abiturientinnen und Abiturienten ein kleines Comeback. Das Prinzip: Die Auszubildenden – kurz Azubis – arbeiten drei bis vier Tage pro Woche im Betrieb und besuchen an den übrigen Tagen die Berufsschule, wo sie Theorie und allgemeinbildende Fächer lernen. Die Ausbildung dauert je nach Beruf zwei bis dreieinhalb Jahre; mit Abitur kann sie oft verkürzt werden. Am Ende steht eine Prüfung vor der Industrie- und Handelskammer oder der Handwerkskammer, die bundesweit anerkannt ist.",
      "Ein wichtiger Unterschied zum Studium: Azubis verdienen vom ersten Tag an Geld. Die Ausbildungsvergütung ist gesetzlich geregelt und steigt mit jedem Ausbildungsjahr. Studiengebühren gibt es an staatlichen Hochschulen in Deutschland zwar in der Regel nicht, doch viele Studierende müssen neben dem Studium jobben, um Miete und Lebenshaltungskosten zu bezahlen.",
      "Hinzu kommt der Fachkräftemangel. In vielen Handwerks- und Industrieberufen suchen Betriebe händeringend Nachwuchs. „Wer eine Ausbildung gut abschließt, hat bei uns praktisch eine Jobgarantie“, sagt Thomas Berger, Ausbildungsleiter in Lenas Firma. Viele Unternehmen bieten zudem an, später berufsbegleitend zu studieren oder einen Meister- oder Technikerabschluss zu machen – ein Weg, der mitunter zu besseren Gehältern führt als ein Bachelorabschluss.",
      "Auch im Ausland stößt das Modell auf Interesse. Immer wieder besuchen Delegationen aus anderen Ländern – auch aus den USA – deutsche Betriebe und Berufsschulen, um zu verstehen, wie die Zusammenarbeit von Unternehmen, Kammern und Staat funktioniert. Kopieren lässt sich das System allerdings nicht so einfach, erklären Fachleute: Es lebt davon, dass die Betriebe bereit sind, Zeit und Geld in junge Menschen zu investieren, die sie selbst ausbilden, und dass Ausbildungsberufe mit klar festgelegten Inhalten überall im Land gleich viel wert sind. Wer als Azubi in Hamburg Industriekaufmann gelernt hat, kann sich deshalb problemlos in München bewerben.",
      "Ganz ohne Schattenseiten ist das System allerdings nicht. Die Qualität der Ausbildung hängt stark vom Betrieb ab; in manchen Branchen klagen Azubis über Überstunden und darüber, dass sie vor allem als billige Arbeitskräfte eingesetzt würden. Außerdem sei der Ruf der Ausbildung in manchen Familien noch immer schlechter als der eines Studiums, sagt die Bildungsforscherin Dr. Anja Seidel. „Viele Eltern denken, Akademiker hätten automatisch mehr Erfolg. Das stimmt so pauschal nicht mehr.“",
      "Lena bereut ihre Entscheidung nicht. „Ich wollte etwas mit meinen Händen machen und trotzdem viel lernen. Genau das habe ich bekommen.“ Ein Studium schließt sie für die Zukunft nicht aus – nur eben nicht direkt nach der Schule."
    ],
    relevant: ["Dual system: 3–4 days a week in a company, rest at vocational school (theory + general subjects)", "Duration 2–3.5 years, often shorter with Abitur; nationally recognised final exam (chambers of commerce/crafts)", "Apprentices earn money from day one, pay regulated by law and rising each year", "Comparison: no tuition fees at public universities, but many students must work to pay rent", "Shortage of skilled workers → very good job prospects", "Interest from abroad (incl. the USA), but hard to copy: companies must invest in training, qualifications have the same value everywhere in Germany", "Further options: study part-time later, master craftsman/technician qualification, sometimes better pay than a bachelor's", "Downsides: quality depends on the company, overtime / cheap labour, lower reputation among some parents", "Example: Lena chose an apprenticeship despite very good Abitur; permanent contract, no regrets, might still study later"],
    irrelevant: ["Exact Abitur grade 1.6 (can be paraphrased as 'excellent grades')", "Grandmother's photos at the trade fair", "Names of the training manager and the researcher", "Baden-Württemberg"],
    cultural: ["'duale Ausbildung' → dual vocational training / apprenticeship combining work and school (compare: US apprenticeships are much less common)", "'Berufsschule' → vocational school", "'IHK/Handwerkskammer' → chambers of commerce and crafts that run the final exams", "'Meister' → master craftsman qualification, allows you to run your own business and train apprentices", "'Abitur mit 1,6' → explain German grading if mentioned (1 = best)"],
    model: "Hey Jayden,\n\nGreat to hear from you! You asked me about apprenticeships in Germany – funnily enough, I just read an article about exactly that, so here is what I found out.\n\nThe German system is called 'dual vocational training' because it combines two places of learning. Apprentices work in a company for three or four days a week and spend the rest of the week at a vocational school, where they learn the theory and also take general subjects. Depending on the job, the training takes between two and three and a half years – with the Abitur, our final school exam, it can often be shortened. At the end, there is a final exam run by the chambers of commerce or crafts, and the qualification is recognised all over Germany.\n\nWhat might be most interesting for you: apprentices get paid from day one. The pay is regulated by law and goes up every year. That's a big difference compared with going to college. Even though public universities here usually don't charge tuition fees, many students still have to work part-time to pay their rent.\n\nThe job prospects are really good at the moment because there's a shortage of skilled workers, especially in industry and the trades. One training manager even said that apprentices who finish with good results practically have a job guarantee. Later on, you can still go to university part-time or become a 'Meister', a master craftsman, which allows you to run your own business – and sometimes that pays better than a bachelor's degree.\n\nBy the way, the article mentions that people from the US have also visited German companies to study the system. Apparently it's hard to copy, though, because it only works if companies are willing to invest time and money in training young people and if the qualifications are worth the same everywhere in the country.\n\nOf course, it isn't perfect. The quality of the training depends a lot on the company, and some apprentices complain about overtime and feel they're used as cheap labour. Also, some parents still think that a university degree is automatically better.\n\nThe article tells the story of a young woman who finished school with excellent grades but chose to train as a mechatronics technician anyway. She now has a permanent contract and doesn't regret it at all – and she says she might still go to university one day.\n\nMaybe that helps you with your decision? If you want, we can talk about it on the phone this weekend.\n\nTake care,\n[Name]",
    why: ["Struktur nach Jaydens Frage (Wie funktioniert es? Erfahrungen?), nicht nach Textreihenfolge", "Kulturspezifisches erklärt: dual system, Abitur, Meister, Kammern", "Vergleich mit dem US-College (tuition, part-time work) für den Adressaten relevant", "Details weggelassen: Note 1,6, Oma, Namen, Bundesland", "Informelles Register (Hey, Take care), aber gegliederte Absätze mit Konnektoren"] }
};
